### ISSUE TITLE
Front end design

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#1]
Tomas created first designs. Please check it so that we can discuss what you like, what should be changed or whether we should change the approach completely. I already have some comments what I like and what s confusing for me but I'd like to hear your first :)

There are three different design for the landing page which slightly differs in colors.
Feedback form and admin interface is not there yet as I'd like to here your opinions on the concept first.

Thanks

![image](https://user-images.githubusercontent.com/17906453/107770290-7812e600-6d39-11eb-87c9-a6d1971dd5aa.png)
![image](https://user-images.githubusercontent.com/17906453/107770315-7d703080-6d39-11eb-8060-2b91e9a8f0eb.png)
![image](https://user-images.githubusercontent.com/17906453/107770327-819c4e00-6d39-11eb-9f83-cc0e3060def0.png)
![image](https://user-images.githubusercontent.com/17906453/107770344-86610200-6d39-11eb-8007-d8f6509cf629.png)
![image](https://user-images.githubusercontent.com/17906453/107770354-8a8d1f80-6d39-11eb-9982-c0f86568ba97.png)

**Comment by sabahfromlondon** [comment]
**Homepage**

- Should say "Search for and access datasets in OCDS by country "Typo with "hlep" should say help
- OCP logo could be bigger
- The first design is the best one, as it is in keeping with the heading design of the website 
- I like the "Start you search" button on the top right

**Datasets by country**

- Country starting with - should have a similar number of letters on each line
- Custom option for the calendar is missing
- It should probably say "Access from OCP's Kingfisher Database" to be clear to the user who may not be familiar with all of the OCP tools and the different bird names
- The different datasets look very compressed. There will not be a huge number of search results, so I think we can allow for more room here in the design. Can we re-think this bit?
- The ticks in the boxes next to OCDS, JSON and Excel look too much like checkboxes that can be un/checked. I would change this. Perhaps use colours too?
- Different shades of grey in the datasets - highly likely there is a contrast error which could adversely impact people with a visual impairment

**Data details page**

- Same comment about the checkboxes as previous screen
- Where does the "Access" button on the top right lead to? Does it just scroll the page down? I think this could be confusing for users?
- How will this page be designed if the data is available in both JSON and Excel? The UI needs to use the tabs approach that I suggested in my updated wireframes. These were shared: https://drive.google.com/file/d/1TMMT8PHdKHciEh_of1ht97dieyV3jq_8/view?usp=sharing and https://drive.google.com/file/d/15KgXQ1JD_oCJuOmMhDYZJcBhbR9I7Mhj/view?usp=sharing
- The open in a new tab icon for the Kingfisher database is not needed
- I think the two "Data quality" sections can be one i.e. there does not need to be a divider between them

**Comment by jpmckinney** [comment]
Home page:

* I prefer the second one (white background behind logo). The dark background on the OCP website makes sense, because it visually separate the top navigation, but here we don't have anything besides the logo, so I prefer to emphasize it less.
* Similarly, I think the OCP logo's size is fine, since it's not a critical element, but we can tweak this later.

Regarding the tabbed design, I agree with Jan on the call, in that it's not obvious to a user that it's the same information with a slightly different wording. I can imagine tabbing between them looking for the relevant difference and then realizing it's just a few words. I think Jan's suggestion on the call of a toggle or option switch near the top of the page might work better. Then we can just do a simple transition or the affected elements, and it's obvious that it's just some words changing.

**Comment by sabahfromlondon** [comment]
**Homepage:**

- No problem with the second option. I just thought OCP wanted alignment with the website :)

**Tabbed Design**

- I did test the tab design with users (admittedly not as many as previous screens) and there was no evidence of confusion. Having said that I don't have an issue with the toggle switch option. Sorry @hrubyjan I didn't realise you suggested this! I'd like to see the design, but in theory I think this should also work.

**Comment by hrubyjan** [comment]
I'll discuss this with Tomas today and we'll try to come with some options for the tabbing/switching issue.

**Comment by hrubyjan** [comment]
Thanks for the initial feedback I now started 3 new issues based on this issue and I'm closing it
- #4 Landing page
- #8 Search result
- #9 Dataset detail
