### ISSUE TITLE
Dataset name and description

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#10]
The front end design does not contain a dataset name and description. It only contains country. What I see in the Kingfisher is several different collection e.g. for Mexico

- mexico_administracion_publica_federal
- mexico_cdmx
- mexico_inai
- mexico_grupo_aeroporto
- mexico_jalisco
- mexico_nuevo_leon_releases
- mexico_inai_portal
- mexico_quien_es_quien

I guess it would be good to have three information
- Country of the dataset which we will use in the search
- Name 
- Description
  - I don't see any information about what data each specific dataset contains. If it's for some region in mexico, only for public institutions like ministries but not for municipalities, ...

What's you opinion on this?

**Comment by sabahfromlondon** [comment]
Hi @hrubyjan I've had a think and a chat with James. Here is how I would like to change the design:

**On the results page:**
- For each result, the title needs to also include the data set name in addition to the country e.g. "Mexico CDMX" or "UK Contracts Finder". I'm keen for this to be clear, for instance what I do **not** want to see is "mexico_cdmx".
- We will also need a one line description below the heading. For instance for UK Contracts Finder: "This dataset contains procurement data published by the UK Government's Contracts Finder portal with information for contracts worth over 10,000 GBP."

**On the data details page**
- The heading needs to match the heading on of the results page i.e. UK Contracts Finder
- The description needs to be added below the title. This should match the ones on the results page.

Let me know if you have any questions. Happy to jump on a quick call or we can discuss in the weekly catch up.

Sabah

**Comment by hrubyjan** [comment]
@jpmckinney do we have the collection country and human friendly name somewhere in the kingfisher or do we need admin to enter it into the data registry?

**Comment by jakubkrafka** [comment]
@hrubyjan nope, it's not there.

**Comment by hrubyjan** [comment]
Admin will have to enter country (UK), title (Contracts finder) and description (This dataset contains procurement data published by the UK Government's Contracts Finder portal with information for contracts worth over 10,000 GBP.)
![image](https://user-images.githubusercontent.com/17906453/113253224-3c21e900-92c5-11eb-95e9-e35dcf546812.png)
