### ISSUE TITLE
Default text for missing qulity summary

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#103]
Please give me a default text for this text box when quality summary is missing

![image](https://user-images.githubusercontent.com/17906453/128036210-d0520f5d-0fc6-4646-a832-ee8dc0df8096.png)

**Comment by yolile** [comment]
With James, we agreed on "We have not yet prepared a data quality summary for this dataset." @sabahfromlondon let me know if that makes sense for you

**Comment by sabahfromlondon** [comment]
Thanks @yolile. The text is perfect

**Comment by t-mrazek** [comment]
implemented

**Comment by hrubyjan** [comment]
For example https://data-registry.datlab.eu/en/collection/17

![image](https://user-images.githubusercontent.com/17906453/128323607-db9e5c1a-f780-4fd0-978f-9957b4ced6b3.png)
