### ISSUE TITLE
Country flags: Paraguay flag is missing

### ISSUE THREAD

**Issue by yolile** [open-contracting/data-registry#110]
![screenshot_5](https://user-images.githubusercontent.com/6834122/129754455-07f53655-9027-4f65-ad1a-ef4d473ed10b.png)
:cry:

**Comment by jpmckinney** [comment]
Weird - the icons include Paraguay, but only in SVG, PSD and EPS. We can create the PNG from those. @yolile Do you have the software for that, or should Datlab do it?

**Comment by jpmckinney** [comment]
After checking, the only other PNG missing is 100-abkhazia.svg. (Paraguay is 260- for when I need to look it up again.)

**Comment by yolile** [comment]
> Weird - the icons include Paraguay, but only in SVG, PSD and EPS. We can create the PNG from those. @yolile Do you have the software for that, or should Datlab do it?

Maybe it was deleted by mistake? I can create the PNG from the SVG

**Comment by jpmckinney** [comment]
Weird - the ZIP I had downloaded and attached in [Slack](https://opencontractingint.slack.com/archives/CK47P2NP8/p1616215648000400) doesn't have the file, but I can get it from https://www.flaticon.com/free-icon/paraguay_555419. @hrubyjan Can you add the paraguay PNG to wherever the flags are stored? 

![paraguay](https://user-images.githubusercontent.com/26463/129758421-411726e7-7e64-4738-8475-4b029292b2c8.png)

**Comment by jpmckinney** [comment]
For completeness, let's also add Abkhazia https://www.flaticon.com/free-icon/abkhazia_555579

![abkhazia](https://user-images.githubusercontent.com/26463/129758905-e477584f-a98b-47da-b940-df972e4f63b8.png)

**Comment by hrubyjan** [comment]
@yolile I've set the flag for Paraguayan sources. It should be a complete set now
