### ISSUE TITLE
Disable selection of future dates in data range filter

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#118]
Yes look good to me now. I think it would also be helpful if the user is not allowed to select a date in the future. Is this possible?

_Originally posted by @sabahfromlondon in https://github.com/open-contracting/data-registry/issues/77#issuecomment-874184984_

**Comment by jpmckinney** [comment]
Can do with a bit of JS (so that caching doesn't cause the max to be in the past) https://stackoverflow.com/questions/23671407/restrict-future-dates-in-html5-date-input

**Comment by jpmckinney** [comment]
Merged into #249
