### ISSUE TITLE
When to run collectstatic command

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#123]
I see there are a mix of auto-generated and manually-created files in `data_registry/static`.

1. Which files are auto-generated?
2. When does an admin need to run collectstatic?
3. Why can't collectstatic be run on the server instead, during deployment?

Found while running:

```bash
find . -type f -not -path '*/migrations/*' -not -path '*/.git/*' -not -path '*/static/img/flags/*' -not -name '*.pyc'
```

**Comment by jpmckinney** [comment]
It seems like static files are deployed to /var/www/data-registry.datlab.eu/static

**Comment by jpmckinney** [comment]
To be specific, I notice a lot of built likes like those in `data_registry/static/admin`, which I don't think should be committed to git, but should instead just be part of the build (whether in CI or on the server).

**Comment by jakubkrafka** [comment]
Typically, we run that only once or two times during the development project lifecycle to collect admin statics. As we don't need that more often, it wasn't included in the build. But, of course, it can be added. 
Auto-generated files are those build by npm in data-registry/vue

**Comment by jpmckinney** [comment]
@jakubkrafka Please just re-assign these issues to me. Otherwise, I either need to keep track of which ones I need to act on in email. They are not done, because I still need to do something with the information you gave.

**Comment by jpmckinney** [comment]
Making a note to run collecstatic in the Dockerfile (following up on #139).
