### ISSUE TITLE
Document shell scripts in /home/datlab

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#124]
Document **what** it does and **when** to use it. Or, delete it if it never needs to be run in production.

* [ ] deployPelican
* [ ] exportConfigForKc
* [ ] restartAndUpdateDqtWorker
* [ ] runDqtWorker
* [ ] updateDataRegistry
* [ ] updateDqtWorker
* [ ] updateKpWorker
* [ ] wipe_collection.sh

I assume wipe_all_unused_collection.sh can be deleted.

**Comment by jpmckinney** [comment]
It looks like a lot of these pull containers from AWS, which we are not using, so it's possible we can just delete it all.

**Comment by jakubkrafka** [comment]
You can delete all of those.

**Comment by jpmckinney** [comment]
Looks like someone has deleted them :)
