### ISSUE TITLE
Document files and directories in production deployment

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#125]
* [ ] What is /data/tmp for?
* [ ] Describe the files/directories within /var/www

**Comment by jpmckinney** [comment]
The /data/kingfisher-collect symlink is used by env files. Can delete once new env files are deployed by OCP/Dogsbody.

**Comment by jakubkrafka** [comment]
/data/tmp - can be removed, there is no special functionality tied to that
/var/www - nothing lives there - besides .htpasswd for the current, testing domain. You want to remove this anyways.

**Comment by jpmckinney** [comment]
Thanks! There was something there, but you already deleted it according to Slack :)
