### ISSUE TITLE
Detail - implementation

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#13]
# Collection header
All information will be the same as for the search reasult item #5 . `Access` button scrolls down to the `Access data` section
- **Flag**
  - Selected by admin
- **Title**
  - Country + human readable dataset name
  - Both entered by admin
- **OCDS label** - static for now, all records has the same value
- **Description**
  - entered by admin
- **Available formats**
  -  both formats always available in MVP

# Overview
- **Data date range**
  - the same information as we display it on a search result item
- **Update frequency**
  - the same information as we display it on a search result item
- **Last update**
  - the same information as we display it on a search result item
- **OCID prefix**
  - let's get it the same way we do for Pelican
- **License** 
  - let's get it the same way we do for Pelican

# Data available

8 sections which follows the same logic as a filtering checkboxes
- Green check if the dataset can be filtered by the corresponding filtering checkbox
- Otherwise grey cross (data not available)

For each **count** information we can take the value from Pelican. It's stored in Pelican as a number of `isSet` check for a subfield of a particular structure.

For example here we know that there is 9084 parties because we checked the presence of `parties.name` or `parties.id` 9084x
![image](https://user-images.githubusercontent.com/17906453/110655858-b75d1700-81bf-11eb-8c11-6b226c39d9eb.png)

List of available data
**Parties**
Count of parties

**Planning**
Count of planning activities

**Tenders**
Count of tenders
Count of tenderers
Count of tender items

**Awards**
Count of awards
Count of award items
Count of awards suppliers

**Contracts**
Count of contracts
Count of contract items
Count of contract implementation transactions

**Documents**
Count of documents related to the different stages of the contracting process
- planning.documents
- tender.documents
- awards.documents
- contracts.documents
- contracts.implementation.documents

**Milestones**
Count of milestones related to the different stages of the contracting process
- planning.milestones
- tender.milestones
- contracts.milestones
- contracts.implementation.milestones

**Amendments**
Count of amendments related to the different stages of the contracting process
- tender.amendments
- awards.amendments
- contract.amendments

# Data quality

- **Summary**
  - mandatory information entered by admin
- **Issues found**
  - optional information entered by admin

# Access data

- **Excel**
  - link to Flatten tool which will pass some information to the flatten tool
    - dataset identification
    - date range
- **JSON**
  - Opens dialog which allows user to download dumps by years and one complete dump

![image](https://user-images.githubusercontent.com/17906453/110654638-9c3dd780-81be-11eb-8af8-667b8133372c.png)

**Comment by jpmckinney** [comment]
From our call and from #9, just a note re: license that we'll need:

* A way for the admin to override the license information (especially if there is none in the data)
* Some sort of mapping from `license` in the data to a canonical URL (e.g. some publishers link to their own page, which just says that it's a certain Creative Commons license)
* Likely some further design work, so that we can also explain what rights and obligations the license confers, since users will not be able to read e.g. a custom Portuguese license

**Comment by jpmckinney** [comment]
@yolile noticed that we don't currently have a link to the original publication. I think we need to add it. Related: #15

**Comment by jpmckinney** [comment]
@sabahfromlondon Can you review this issue, and close if appropriate?

**Comment by sabahfromlondon** [comment]
All the fields required in the 'Data Available' are as required.
