### ISSUE TITLE
Where to change logging configuration for /data/logs/dqt.log

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#130]
It's already 4GB. I'll either change the logging level to warning, or ask Dogsbody to set up log rotation.

**Comment by jpmckinney** [comment]
```
grep -vE 'INFO|DEBUG' dqt.log | wc
```

returns less than 1MB.

**Comment by jpmckinney** [comment]
It's the log_filename and log_level settings in pelican-backend.

**Comment by jpmckinney** [comment]
@hrubyjan Please let me know if you've found it useful to read the DEBUG-level and INFO-level messages.

**Comment by hrubyjan** [comment]
I think you don't need DEBUG and INFO messages. Message content (dataset or items ids) should be repeated in ERROR message which is important when something goes wrong

**Comment by jpmckinney** [comment]
Thanks!
