### ISSUE TITLE
How was certbot installed and configured

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#131]
OCP instead uses https://github.com/icing/mod_md

Dogsbody will need to know how to undo your changes.

**Comment by jakubkrafka** [comment]
Certbot was probably installed in a default way with the packaging system (zsh was deleted:(). But in general, we never install binary versions downloaded somewhere, but use the "proper" way instead. As the apache server, where certbot is used, will/has to be reconfigured by Dogsbody anyways, you can continue to use it, or remove it simply with apt.

**Comment by jpmckinney** [comment]
The zsh history file is still there, and that is how I found that certbot was installed.
