### ISSUE TITLE
Environment files documentation and changes

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#136]
I'll log here changes I've made, as I make them.

* data-registry.env
  * Change ENVIRONMENT=production (was development)
  * Remove DEBUG=on
* dqv.env (pelican-frontend)
  * Remove DEBUG=yes
  * There is no `django` schema, so I removed it from `DEFAULT_DB_SEARCH_PATH=django,public`
* Fixed SENTRY_DNS -> SENTRY_DSN typo (and in repos). It stands for Data Source Name.

**Comment by jpmckinney** [comment]
Okay, my questions:

* When should a developer change the STATIC_VERSION environment variable? #
* What does ENVIRONMENT control?
* https://github.com/open-contracting/pelican-backend/issues/27

**Comment by jpmckinney** [comment]
`STATIC_VERSION` has no effect, because the Dockerfile overwrites it in `settings.py` to a date, instead of reading from the environment.

**Comment by jakubkrafka** [comment]
For a current build, STATIS_VERSION has no effect. However - this can change for other deployment scenarios.

**Comment by jpmckinney** [comment]
Re-opening and reassigning because I actually have to do something with this info.

**Comment by jpmckinney** [comment]
@jakubkrafka You said you would look into the `ENVIRONMENT` variable. As far as I can tell, the code doesn't use it.

Please re-assign to me after answering.

**Comment by jakubkrafka** [comment]
Can be removed from the .env file. It's just a copy&paste mistake.
