### ISSUE TITLE
Document how to access Rabbit management interface

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#137]
e.g. do you need to create an SSH tunnel?

**Comment by jpmckinney** [comment]
Also, it seems like Rabbit is in a container, and that this file is managed in pelican-backend, which is very unusual, because the service is used by Kingfisher Process, pelican-frontend and the Data Registry as well.

https://github.com/open-contracting/pelican-backend/blob/main/docker/rabbit/Dockerfile

Can you explain how Rabbit is deployed (an explicit series of specific commands would be best), so that we can move it out of that repository?

**Comment by jakubkrafka** [comment]
Tunnel:
```
ssh -N amy01 -L 15672:localhost:15672
```

Rabbit deployment in docker is purely optional, can be done like this (its default state. nothing special):
```
docker run -d --name rabbit -p 5672:5672 -p 15672:15672 -e RABBITMQ_DEFAULT_USER=rabbit -e RABBITMQ_DEFAULT_PASS=rabbit  rabbit
```

Note: The docker in dqt increases default value of just one parameter - consumer_timeout. As the messaging has been rewritten completely, its not needed anymore.

**Comment by jpmckinney** [comment]
Hmm, not sure what I'm doing wrong. From my machine:

```
ssh -N ssh://root@ocp13.open-contracting.org:2223 -L 15672:localhost:15673
```

Since I already have RabbitMQ locally, I bound to `15673` instead (unless that's the wrong one to change).

I figure I will undockerize RabbitMQ. I need access to the admin to check that there are no messages in any queues.

Also, as I understand, Kingfisher Process declares the queue, but Kingfisher Collect does not. I think I might change Kingfisher Collect to declare the queue as well, otherwise we need to very carefully do the first deployment, because if the queue isn't declared by the time Kingfisher Collect runs, the messages will just be dropped by RabbitMQ.

I don't know if there are similar interdependencies between other components. In general, I think any publisher of messages should declare the queue.

**Comment by jpmckinney** [comment]
@hrubyjan Based on your experience, what common things do you do in the RabbitMQ interface? e.g. what do you look for within which dashboards, and do you just use it to read information, or do you perform any actions?

From my quick look, the Queues tab is most useful to see what work is left to do (right now, there's a lot in the Checker, because lib-cove-ocds is slow, but also not needed by the registry).

In terms of undockerizing, it looks like we should scale all non-web workers down to 0, delete the Rabbit container in its current state, and create a new container.

However, I'm not clear on which apps declare the exchanges, queues, etc., so I'd like confirmation that both publishers and consumers declare them (otherwise, errors are likely to occur).

**Comment by hrubyjan** [comment]
@jpmckinney right I use only the Queues tab to monitor the work progress. 
Sometimes I go to the queue detail to
- send a message (not when using data registry as all tasks can be started from the admin interface but maybe you'll run into a situation when you can use it)
- see the long-term message rate so that I can estimate when the work will be done

The rest we discussed on a call. Queues are created by the consumer. From your perspective the best is to create queues once and then don't delete them as you have a low limited number of queues which will not make your UI chaotic. And what's important you always need all the queues. You can always `purge` messages

**Comment by jpmckinney** [comment]
Added to admin guide.
