### ISSUE TITLE
Confirm what Dockerfile_static does

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#139]
As I understand, it builds the Vue files, serves them with Nginx on port 8003, and then Apache has a ProxyPass to Nginx. This seems rather redundant. Is there any advantage to using Docker here?

If it makes no difference, I'll just use Salt to build the files on the server, and serve them directly from Apache.

Related: #125, because Apache is also configured to serve the static files in /var/www/data-registry.datlab.eu

**Comment by jakubkrafka** [comment]
Yes, it serves the static files. And of course, you can build this on the server. I will not recommend that, as you will have to maintain the whole "development" infrastructure on the server itself.

#125 is just an old artifact, was removed.

**Comment by jpmckinney** [comment]
Okay, please answer #123, as it is not clear when/how to build the static files. (I think it is rather unusual to commit built files to git. Typically, CI does the build...)
