### ISSUE TITLE
JSONL guidance/admonition

### ISSUE THREAD

**Issue by yolile** [open-contracting/data-registry#141]
In the UI we mention that you can download the data as JSON or Excel, but actually, the JSON file is a JSONL file. Should we mention this in the JSON download modal? eg after mentioning the GZ format: 
![screenshot_9](https://user-images.githubusercontent.com/6834122/131388623-37155336-e7f3-45cf-8988-36506eb6eb17.png)

cc @sabahfromlondon @jpmckinney

**Comment by jpmckinney** [comment]
Yes, we should!
