### ISSUE TITLE
Admin interface

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#15]
# Implementation
We will use Django admin to allow administrator to add information "static" for a given source, schedule source scraping, publish collections etc.

We will customize Django admin so that it's user friendly

# Collection status
- published
  - this collection is available for all users 
- unpublished
  - this collection can be only displayed by admin
- scheduled
  - this collection is regularly updated
- frozen
  - this collection won't be updated anymore but the data are still published

all collections are either `published` or `unpublished`
all collections are either `scheduled` or `frozen`

Statuses should be displayed for the admin only

# Progress
Collect, Process, Pelican, Export
Progress overview has to be available to the admin. See #32 for jobs and tasks statuses and results

# Data

- Source
  - select one from the list of sources. One source means one Collect's spider
  - this can be only changed if no job started for this specific source
- Job
  - all available jobs that finished for the given source
  - admin can select any of the finished jobs and say `Publish`
- dataset country
  - **editable by admin**
  - country selector 
  - linked with the flags catalogue. Flag displayed on a dataset detail or in the search result item will be dependent on the country value selected by admin
  - flags attached
[555416-rectangular-country-simple-flags (1).zip](https://github.com/open-contracting/data-registry/files/6241670/555416-rectangular-country-simple-flags.1.zip)

- Source name
  - **editable by admin**
  - human friendly name of the dataset
- Source language
  - **NEW** field in a model
  - **editable by admin**
  - One word - e.g. English, Spanish
- Source description
  - **editable by admin**
  - short description, free text, 1-2 sentences
- Source long description
  - **NEW** field in a model
  - **editable by admin**
  - for some datasets we can also have a longer description including several paragraphs and bullet list
- Scraping frequency
  - **editable by admin**
  - monthly / 6 month / annually
- Additional data
  - **NEW** field in a model
  - **editable by admin**
  - Free text
- Data quality summary
  - **editable by admin**
  - Free text with a build in markup language processing
- Data quality issues found
  - **editable by admin**
  - itemized list of issues
- License
  - we will have a catalogue of licenses, their urls and explanations (Admin has to be able to explain what rights and obligations the license confers, since users will not be able to read e.g. a custom Portuguese license)
  - information extracted from data
    - URL - static information that can't be changed but will be only displayed to an admin
  - admin input
    - admin will select one license from the license catalogue which will be eventually displayed to the general user

# Actions

- Schedule collection publishing
  - this collection should be regularly updated
- Freeze collection update
  - do not update this collection anymore but keep the data
- Publish collection
  - make the collection public
- Unpublish collection
  - data are stored in the system but the data are not public anymore
- Remove collection
  - permanently remove
  - this needs to be confirmed

**Comment by jpmckinney** [comment]
For country flags, I haven't read the license. Please check our use respects the license: https://www.freepikcompany.com/legal#nav-flaticon-agreement

**Comment by sabahfromlondon** [comment]
I just read the licence agreement. Two things:

1. The only issue I see is that they don't allow users to transfer the content. In other words Ventures Consulting sending the OCP the flag icons and then OCP using them, is in breach of the licence.  

Action => @jpmckinney I suggest that you create a Flaticon account and re-download the logos. I think this is the one: https://www.flaticon.com/packs/rectangular-country-simple-flags?word=flags

2. We need to attribute the logos. We need to use the link that is provided. Here it is for the flags pack above: <div>Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>

**Comment by sabahfromlondon** [comment]
@hrubyjan some additional points of clarification. Hope this helps :)


Information | Format | Example(s) | Mandatory
-- | -- | -- | --
Name of dataset country | No acronyms | United KingdomMexico | Yes
Name of data source | One or multiple words | Contracts FinderAdministracion Publica Federal | Yes
Source description | Free text. Approx 1-2 sentencesInclude URL for source | This dataset contains procurement data published by the UK Government’s Contracts Finder portal with information for contracts worth over 10,000 GBP. | Yes



Name of dataset country:

-

**Comment by jpmckinney** [comment]
@sabahfromlondon Can you review this issue, and close if appropriate?

**Comment by sabahfromlondon** [comment]
@hrubyjan what is the definition of done for this issue? 

I can see that there is data missing or sample data in the front-end for multiple datasets. I didn't report issues because I thought this was work in progress.

**Comment by sabahfromlondon** [comment]
I can confirm that we have **all** the fields in the 'data details page' that are required for this issue to be closed 

FYI: Separate to this issue we need to check that all fields contain data and that data is correct. We also need to test the admin panel.

**In the Heading Section**
Country 
Dataset title 
OCDS label
Available formats - JSON 
Available formats - Excel
Data overview

**In the Overview Section**
Data date range
Last updated
Update frequency
OCID prefix
License
Language

**In Data quality Section**
Data quality summary
