### ISSUE TITLE
Move admin guide to ReadTheDocs for this project

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#155]
* [x] https://docs.google.com/document/d/1iMxMEheQw3656Lxi4d9zZ01KR536EnBhqJFLvzNpfrw/edit

**Comment by jpmckinney** [comment]
System diagram: https://app.diagrams.net/#G1bFbyop37OwbLrhbPaGbLUL6_TWkBs6GH

**Comment by jpmckinney** [comment]
@yolile Should we move part of https://docs.google.com/document/d/12d61HXZaD3wBYN479ShfZmc0xW29fJvmGNhkyf4xUhg/edit to the docs, too?

**Comment by yolile** [comment]
Yes, I think we could include the steps about adding a new publisher
