### ISSUE TITLE
Dataset detail: Highlighting notable features

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#16]
This issue is for discussion, as the best approach isn't clear yet.

Some publishers make interesting use of extensions. For example, Afghanistan has a lot of metrics data, Colombia has gender data, Paraguay and Moldova have complaints data, etc.

We could author this manually at the end of the dataset description. However, there are a few concerns:

* Placement: This information belongs more in the "Data available" section.
* Preparation: We don't have the time to analyze each dataset in order to manually author this content. So, we will only have highlights for the datasets we know best / for which we've prepared data feedback reports.
* Publisher requests: I anticipate that a manual approach will mean that some publishers will contact us to highlight features in their data, at which point we need to make an editorial decision.

That said, maybe the benefit to users is greater than these concerns.

Alternatively, we can work on an automated approach, though I also anticipate challenges there, both in terms of determining what to highlight, and in terms of keeping the "Data available" section brief and useful.

**Comment by jpmckinney** [comment]
@sabahfromlondon What do you think about this issue?

Example for Paraguay:

> Besides core OCDS fields, Paraguay also publishes other relevant information through some OCDS recommended extensions, such as [lots](https://extensions.open-contracting.org/en/extensions/lots/master/), [bids](https://extensions.open-contracting.org/en/extensions/bids/master/), and [enquires](https://extensions.open-contracting.org/en/extensions/enquiries/master/). They also created some useful local extensions to disclose data related to [complaints](https://gitlab.com/dncp-opendata/ocds_complaints_extension), [bid items](https://gitlab.com/dncp-opendata/ocds_bid_items_extension), [auctions](https://gitlab.com/dncp-opendata/ocds_auctions_extension), links to [investment projects](https://gitlab.com/dncp-opendata/ocds_planning_investmentproject_extension), [item attributes](https://gitlab.com/dncp-opendata/ocds_item_attributes_extension), among others.

**Comment by sabahfromlondon** [comment]
@jpmckinney @yolile

In my mind I had details about the additional fields / extensions in the "data quality summary", but I agree this is not right place for the content and it would be better to include this information in the "data available" section. 

I think the description below the title should be succinct and 1-2 sentences. 

If it's not too much trouble for the MVP then I would suggest we add the following:

- Data contains additional fields: yes/no
- Data uses OCDS recommended extensions: lots, bids, enquires OR none
- Additional information:
"Paraguay have also created some useful local extensions to disclose data related to complaints, bid items, auctions, links to investment projects, item attributes, among others."

We can only feed back on the dataset's we know about, so there shouldn't be any pressure to provide lots of detail for all datasets if we don't have it. I do think that where we can better inform users, this is very helpful information. Best to keep it manual for now if that's ok.

Almost every user I spoke to said it was frustrating trying to understand: what's in the dataset, what isn't, what's the size, what are the issues and what's weird about it. 1-2 users were even eager to help and provide their feedback on what they found when working with the data!

What do you think?

**Comment by jpmckinney** [comment]
Let's start with the manual additional information free-text paragraph.

I suspect most datasets contain additional fields. @yolile: Do you know?

**Comment by yolile** [comment]
> I suspect most datasets contain additional fields. @yolile: Do you know?

I checked our Kingfisher database and at least 32 different source_ids report at least 1 additional field in `cove_output->'additional_fields'`, so yes.

**Comment by hrubyjan** [comment]
To sum up for visualization purposes
1) it's a positive information that there is something useful besides core OCDS
2) it belongs to `Data available` section
3) the fact that some additional data are available should catch user's attention as it will be not present for all collections
4) we'll start with a short paragraph 

@jpmckinney I see links so this should be some kind of rich text or is it sufficient when HTML is allowed so that admin can simply use `<a href=....>` tag?

**Comment by jpmckinney** [comment]
Yes, either HTML or Markdown. Markdown might be easier to write and safer to transform.

**Comment by jpmckinney** [comment]
For Markdown to HTML I strongly recommend https://pypi.org/project/markdown-it-py/

**Comment by jpmckinney** [comment]
(3) is too prominent in terms of its relative importance on the page. I'm fine with (1) or (2).

**Comment by sabahfromlondon** [comment]
I like the first one the most, so looks like we are all agreed.

**Comment by hrubyjan** [comment]
New development requirement #39 was created based on this discussion
