### ISSUE TITLE
jobs: remove old notes from tasks when the job's status is changed

### ISSUE THREAD

**Issue by yolile** [open-contracting/data-registry#168]
Right now, if a job's task was unsuccessful and then we change its status to "PLANNED" again to re-run it, the old "note" will be still there eg in:

![image](https://user-images.githubusercontent.com/6834122/137017937-7182047e-128f-4edd-bb9d-728d7db7194e.png)

The scrape task was first unsuccessful, due to the error noted in the "Note" column, but the second time the result was OK, but the old note is still there, which is confusing.

**Comment by jpmckinney** [comment]
Closed by linked commit above. The note will only be updated once `manageprocess` (was `cbom`) runs, but that happens every 5 minutes as currently configured, so I think that's good enough.
