### ISSUE TITLE
Clearing filters

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#19]
I ran into a problem when selected a starting letter and then I was thinking how to display all datasets 🤔 . Eventually I figured out that I have to click the letter again but it took me some time. Therefore I think it would be useful to have some control element that allows user to either
a) clear all filters
or
b) clear only the letters filer

**Comment by hrubyjan** [comment]
One more option. Right now the letter is only underscored, maybe if there is a background color it will be more obvious that second click will deselect the letter
![image](https://user-images.githubusercontent.com/17906453/113251853-48a54200-92c3-11eb-9619-fb7dcdb82e66.png)

**Comment by sabahfromlondon** [comment]
I've attached a screenshot of how I think this should look.

Regarding the letters:
- We should have the letters for which there is data highlighted and underlined
- The remaining letters should still be included but not clickable. This is so not to disorientate the user

Additional behaviour:
- When the user lands on the page and no letters are selected, the all results should be presented
- When the user clicks on a letter e.g. the letter U, then only those countries starting with U will appear
- If a user then click on a different letter e.g. C, then all the countries starting with U are replaced with countries starting with the letter C
- If the user clicks the "Clear" button then the results revert back to when the user first landed on the page and all the results are presented again.

Does this sound ok to you? :)

<img width="500" alt="Screenshot 2021-04-09 154305" src="https://user-images.githubusercontent.com/11212467/114197536-5ce3e180-994a-11eb-9133-06f482573f2f.png">

**Comment by hrubyjan** [comment]
Sound good ;)!

The question is whether the `Clear` button is just for this filter or all filters. 
I would also keep the feature when the user turns off the letter by second click on it.

**Comment by hrubyjan** [comment]
Some designs. I like the first one :)
![image](https://user-images.githubusercontent.com/17906453/114529126-eeed3200-9c49-11eb-9b62-5c92fe8572ba.png)
![image](https://user-images.githubusercontent.com/17906453/114529155-f7456d00-9c49-11eb-9f7f-969bceaeff39.png)
![image](https://user-images.githubusercontent.com/17906453/114529175-fdd3e480-9c49-11eb-9036-8e453ad2130f.png)

**Comment by sabahfromlondon** [comment]
I like the clear option in the second one.  

Don't mind how we highlight the letters, both options look good.

I think the clear button should only be for the letters.

**Comment by jpmckinney** [comment]
* I like the highlight of selected letters in the first option. It's more obvious.
* I prefer the line-through-a-funnel icon in the first option, instead of the simple X icon. It's more semantic.
* "Clear selection" or "clear filter" is more specific than "Clear", but if we want fewer words then "Clear" is okay.
* @sabahfromlondon Should there be a "clear all filters" (or "clear all selections") option to easily reset all filters?

**Comment by sabahfromlondon** [comment]
Sorry missed this one. There are not many filter options so a clear all filters is overkill if you ask me.

**Comment by hrubyjan** [comment]
New development requirement #40 based on this discussion
