### ISSUE TITLE
Hyperlink is a contrast error

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#199]
The yellow font is not clear at all. Suggest we switch to using the purple OCP colour. 

Upon hover we should keep the same purple font colour, but add the underline as is the behaviour currently. 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/11212467/158639534-3d1c449a-6a71-4705-b444-6188c11a566c.png">

Same issue on the country page here:

<img width="440" alt="image" src="https://user-images.githubusercontent.com/11212467/158640063-c3077fc2-4862-45fd-a671-1a847cc17dd3.png">

And here:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/11212467/158640170-5216f01e-ede8-47ad-9eaa-dca4e0e2bacd.png">

**Comment by yolile** [comment]
In the next deployment, the links will look like 
![image](https://user-images.githubusercontent.com/6834122/159778200-91bd4436-f162-468c-8454-0b30e8c7489f.png)
