### ISSUE TITLE
Complete set of letters in the filter?

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#20]
James raised the question whether we should have complete set of letter in the filter or we should only have letters for available countries?
![image](https://user-images.githubusercontent.com/17906453/113251982-7e4a2b00-92c3-11eb-8258-713f7249e9c4.png)

I think we should have all letters as missing letters only confuse user. 

a) Why is `V` missing? I need data for Vietnam
b) Aha there is not dataset for Vietnam

**Comment by jpmckinney** [comment]
I think it should be obvious that the letter is missing because no countries match, e.g. an e-commerce website doesn't list product categories it doesn't offer in a dropdown, but I'm open to the possibility that this is not obvious.

**Comment by sabahfromlondon** [comment]
I think there is precedence with filtering with letter that all letters of the alphabet are included (https://uxdesign.cc/making-lists-easy-e7c5d971d1f7). We should stick with that metal model. Making a letter non-clickable, should tell the user that there is no data and that we have not forgotten a letter

**Comment by hrubyjan** [comment]
agree. Nicely described in #19

**Comment by hrubyjan** [comment]
New development requirement #40 based on this discussion
