### ISSUE TITLE
Russian translation is not working properly on results page

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#201]
See screenshot below.

When selecting Russian as the language, some of the content is instead translated into Spanish, while some of it remains in English. 

This appears to happen for the dataset titles and the summaries. 

The dates appear not be translated into Russian at all.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/11212467/158642081-f63345d1-c62f-4322-8f52-cd344fd41779.png">

**Comment by yolile** [comment]
@sabahfromlondon, as mentioned in #203, the details and names are translated into Russian for just a few publishers. The date issue was resolved in #207. We are using the original publisher name for the titles, so publishers from Latam countries will have their names in Spanish even if the language is set to English or Russian.
