### ISSUE TITLE
Information on data details page not translating into Russian

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#203]
See screenshots below. 

The text is still in English for the dataset summary
<img width="700" alt="image" src="https://user-images.githubusercontent.com/11212467/158644129-40942007-2156-42d4-b3f5-45268369e457.png">

The text is still in English for the dates and the licence details
<img width="700" alt="image" src="https://user-images.githubusercontent.com/11212467/158644371-74e6a093-ea4c-4cfb-af87-f6b5a2a781fe.png">

The text is still in English for the info on the available fields info box
<img width="650" alt="image" src="https://user-images.githubusercontent.com/11212467/158644429-b13c718d-e648-4246-bca8-9ac5a1e1ae7b.png">

The text is still in English for the data quality section
<img width="668" alt="image" src="https://user-images.githubusercontent.com/11212467/158644491-78d5fbc0-4650-4f99-9f3d-cd6fa9bb802f.png">

**Comment by yolile** [comment]
@sabahfromlondon the content in Russia is only available for a few publishers, the ones from ECCA, for example, Moldova or Kyrgyzstan https://data.open-contracting.org/ru/publication/29. However, the dates are not translated into Russian even for these datasets, so I will fix that
