### ISSUE TITLE
Visually distinguish which sources do not publish data anymore

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#21]
From @jpmckinney in #9:

there are about 10 for which we can collect data but who have stopped publishing

We can leave the page as-is for now. It just got me thinking that if the number of stopped/paused publishers grows, we should be clearer to the user that this is a concern

**Comment by yolile** [comment]
right now we have the label "Update frequency:" that will be empty for the frozen publications, maybe we can add a text here saying that the publisher doesn't update its data anymore, or similar, what do you think @jpmckinney @sabahfromlondon?
Something like: 
![screenshot_6](https://user-images.githubusercontent.com/6834122/129759283-0f076614-66d8-4940-81aa-214c759a6333.png)

**Comment by sabahfromlondon** [comment]
@yolile - the idea was that the date in the "Last updated" field would indicate that the data is no longer being updated if that is the case.

"Update frequency" tells the user how often the data was updated when data was being published. This is useful if the user wants historical data.

If you think "Last updated" is not clear then perhaps I can suggest the text could change to "Last update by source" or something like that?

**Comment by yolile** [comment]
> "Update frequency" tells the user how often the data was updated when data was being published. This is useful if the user wants historical data.

Ah, but if I'm not wrong, from the admin site, this file is currently used to determine how often **we** update the data. 

Either field works for me, but we need to clarify to the user: a) when was the last time that **we** updated the data, and b) the last time the **publishers** themselves updated the data. Eg: the publishers can update their data every day, but then we only update the dataset every month, so the user should be aware that the original publication can have more data.

**Comment by jpmckinney** [comment]
I think the date range is the relevant information – I don't think it's necessary to indicate the date on which the publishers updated the data. (For example, for Uruguay's historical data, the date range might end in 200X since it is historical, but they might have created/updated it in 2020. I don't think the 2020 date matters.) Also, we can't know when the publishers updated their data until we collect it ourselves, anyway.

Anyhow, we should be clear that "Last updated" is when *we* last collected the data.

For "Update frequency", I don't understand how it is useful for data that is no longer updated. Also, the only options currently are monthly, semi-annually, and annually, but we know many publishers that make updates daily. So, if it is about *our* update frequency, it should just be "off" for frozen publications. If it should actually be about the publisher's update frequency, then we need more options, like "daily".

**Comment by sabahfromlondon** [comment]
@jpmckinney update frequency can be very helpful for end users. 

For example this screenshot of the two Georgia datasets - one updated monthly and one every 6 months. Depending on the use case/ type of analysis the user wants to do, one dataset will be preferred over another, so this is very helpful information to provide.

My intention was always to have the two fields "Update frequency" and "Last updated" to be about the publisher, not us. A daily option was included in the wireframes, but I was told that there were no daily updates, so we removed that option from the faceted search.

<img width="465" alt="Screenshot 2021-08-19 095850" src="https://user-images.githubusercontent.com/11212467/130040355-0038dd8d-cb5f-4d93-84ee-dc632961dbea.png">

**Comment by jpmckinney** [comment]
Right now, "Last retrieved" is a datetime field, and it's currently autopopulated. If we wanted to replace the date in the UI with some text like "This dataset is no longer updated by the publisher.", then I think we will need a checkbox in the admin.

To close this issue, is that all that's left to do?

**Comment by sabahfromlondon** [comment]
It's helpful for the user to know **when** the publisher stopped publishing and much more so than "Last retrieved". Is it possible to do that?

**Comment by jpmckinney** [comment]
Yes, that would be the end date in the Data date range.

**Comment by sabahfromlondon** [comment]
Ok I didn't take it as a given that the last updated date would always be the same as the end date range. If it is then fine.

**Comment by jpmckinney** [comment]
Coming back to this issue, we can either:

1. Replace Update frequency with "This dataset is no longer updated by the publisher."
1. Add "This dataset is no longer updated by the publisher" next to Data date range

I don't understand the use case for knowing how frequently some old data used to be updated, so I'd go for 1.

**Comment by sabahfromlondon** [comment]
I don't think I want to do with either. Even if the publisher has stopped updating the dataset, what data was published historically we should keep both the fields "Update frequency" and "Data date range". 

I think we need to add a new field here. 
- Is the data is being updated by the publisher or not? (Yes/No)
- If No, then we add the statement
- I would tweak thw wording slightly to: "This dataset is no longer being updated by the publisher."

We also need to decide at what point do we mark a publisher as inactive e.g three cycles (essentially the update frequency) of inactivity?

How does that sound?

**Comment by jpmckinney** [comment]
Clarified on call that option (2) is fine (addition not replacement). It would require a new field on the backend. We can perhaps overload the new field from #234 i.e. if retrieval_frequency is "never" then the publisher stopped publishing.

> We also need to decide at what point do we mark a publisher as inactive e.g three cycles (essentially the update frequency) of inactivity?

I think this will be a case-by-case basis, as sometimes the publisher has stopped, but through our work with them, we know that they are working toward re-activating the publication.

**Comment by jpmckinney** [comment]
I'll mark as blocked on #234, which needs to add the new field.
