### ISSUE TITLE
Available formats as booleans in the data model

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#22]
Currently the available data format is static information as it is designs
JSON = true
Excel = false

![image](https://user-images.githubusercontent.com/17906453/113691963-51d04d80-96cd-11eb-875c-f604a0755074.png)

This should be two booleans in the collection data model which are both by default true but we should be able to change the value if we need to run the data registry without a flatten tool that will provide excel files.

**Comment by t-mrazek** [comment]
the collection data model updated and templates refactored
