### ISSUE TITLE
Export: Add missing authorization

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#232]
* [x] Exporter view should only allow access to active job (can change view to only take spider as argument)
  * Instead of taking `job_id` as a parameter, it should just always select the active job (better for search engines, too)
  * Instead of `full` and `year`, just pass the desired basename
  * Change the URL to be a sub-path of the publication, e.g. /publication/4/download?name=full.jsonl.gz
* [x] Add authentication filtering to export view, i.e. so that active jobs of unpublished collections can't be accessed
  * Can use the `collection_queryset` helper

**Comment by yolile** [comment]
Note: a data user emailed us requesting stable URLs for downloading the files, so we could prioritize this.
