### ISSUE TITLE
Separate update_frequency from retrieval_frequency

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#234]
Currently we have a field named `update_frequency` that is used (1) for scheduling crawls and (2) to display the (so-called) "update frequency" to users. However, users are more interested in the source's update frequency than they are in our retrieval frequency (see @sabahfromlondon's comments in #21). The issue is we can't retrieve as frequently as sources update (real-time, daily, etc.).

So, we need to have two fields: one to describe the source's update frequency, and one to set our retrieval frequency.

The retrieval frequency could perhaps be shown in parentheses next to the "Last retrieved:" value.

**Comment by jpmckinney** [comment]
I'd say:

1. Alter column to rename update_frequency to retrieval_frequency. This can be one migration.
1. Add column named update_frequency. I think it's best to simplify the possible values for users, so a text field with choices of:
  * Real time
  * Daily
  * Weekly
  * Monthly
  * Annually

We can add more options as needed, e.g. "Every 6 months"

**Comment by yolile** [comment]
👍🏻 And real-time will be anything less than Daily? E.g., every 15 minutes will be real-time? 1 hour?

**Comment by jpmckinney** [comment]
We can add "Hourly", etc. if they are real options.

**Comment by yolile** [comment]
Okay, I can do the research first, and then we can decide on the values

**Comment by jpmckinney** [comment]
Sure – adding a new choice is easy, so if we don't have the research for them all, we can just default to the retrieval frequency, and add new choices later.

**Comment by yolile** [comment]
Should we also rename `last_update` to `last_retrieved` as part of this? In the UI, this field is already called Last retrieved, not sure why the model wasn't updated as well.

**Comment by jpmckinney** [comment]
The model was updated (`verbose_name`).

We typically don't edit the field name (`last_update`) as this causes a migration, which creates an extra step during deployment (and thus a period during which the application is broken).

We could rename the field and then add `db_column="last_update"`. We haven't done that in the past because it's easier to reconcile the model with the DB if the fields are the same as the columns.

**Comment by yolile** [comment]
> as this causes a migration, which creates an extra step during deployment (and thus a period during which the application is broken).

Aha, but we are adding a migration as part of this PR anyway (to rename update_frequency to retrieval_frequency), so maybe we can rename it too to avoid confusions?
