### ISSUE TITLE
OCDS label alignment

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#24]
The OCDS label should be vertically centered as designed
![image](https://user-images.githubusercontent.com/17906453/113692991-66f9ac00-96ce-11eb-8184-c89891d7b824.png)

It's too low
![image](https://user-images.githubusercontent.com/17906453/113692906-534e4580-96ce-11eb-8bbd-e9130cc7ab81.png)

I'm not sure how this will work when the title line breaks into two. I'm open to discussion @t-mrazek ;)

**Comment by t-mrazek** [comment]
The vertical position of the label element fixed. The label is the inline element and it behaves like a text. For more lines of the text, it will simply be on the end, like a regular text.
