### ISSUE TITLE
Available formats: show in gray the non-availble ones

### ISSUE THREAD

**Issue by yolile** [open-contracting/data-registry#243]
In:
- Each card on the search page
- The details page

**Comment by jpmckinney** [comment]
The template logic is already there. The problem is in the model.

I think you need to set `excel_format` and `csv_format` on the relevant collections to False.

We can change the default to False, and update Exporter (`json_format`) and Flatterer to set them to True.

**Comment by jpmckinney** [comment]
It depends what these are meant to communicate: what formats the registry offers, or what formats the source offers. I figure it means what the registry offers, since few publishers offer more than one format.

So, we can drop the columns and read from the filesystem.

**Comment by jpmckinney** [comment]
Note that there are currently 14,000 files across all jobs (not sure if all are active). I assume it's fast to iterate over this number to build the search page. (For the individual pages, we need to iterate anyway.)
