### ISSUE TITLE
flattener: the tmp file is deleted before the second attempt

### ISSUE THREAD

**Issue by yolile** [open-contracting/data-registry#248]
Causing ["file not found" exception](https://sentry.io/organizations/open-contracting-partnership/issues/3613821761/?project=5823905&query=is%3Aunresolved)` and the CSV files are never generated.

**Comment by jpmckinney** [comment]
Ah, I’ll need to test whether the entire temporary directory gets deleted, or just the file. Not sure why only the file would be deleted

**Comment by jpmckinney** [comment]
Oh, it’s because force=True deletes the output directory, and I had made it the current directory. Just need to change it to a subdirectory
