### ISSUE TITLE
Long description

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#25]
## Long collection description
- We agreed there will be a short description for all datasets
- But for some datasets we can also have a longer description including several paragraphs and bullet list
  - this is a new field in the data model
  - this will be "expandable" when it's present. Something like `read more`
 
![image](https://user-images.githubusercontent.com/17906453/117829891-73e06100-b273-11eb-8990-dcf616c86aeb.png)
![image](https://user-images.githubusercontent.com/17906453/117829938-7cd13280-b273-11eb-9c88-3cf90959c27b.png)

**Comment by sabahfromlondon** [comment]
Yes I think so. Looks like what we agreed :)

**Comment by t-mrazek** [comment]
implemented
