### ISSUE TITLE
Show file sizes as part of the download section

### ISSUE THREAD

**Issue by yolile** [open-contracting/data-registry#253]
Some files are huge (e.g., 5.8 GB for the full CSV file for Colombia) the users should be aware of before downloading the files they want.

**Comment by jpmckinney** [comment]
> Noting that if size is less than 0.1 MB, we just display 0.1 MB (instead of 0.000001 MB for a 1 byte file, or more realistically 0.0001 for the Nuevo Leon files).
>
> If we want to be more correct (given imprecision for files smaller than 0.1 MB), we can display "< 1 MB" if it's less than 1 MB, instead of 0.9 MB, 0.8 MB, etc.

@sabahfromlondon Do you have an opinion?

**Comment by jpmckinney** [comment]
Sounds good. I've made that change. It'll appear next time we deploy.
