### ISSUE TITLE
Add link to OCDS documentation primers in the Registry 

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#258]
Suggestion is to add three links to Registry:

1. [What is the OCDS and why use it?](https://standard.open-contracting.org/latest/en/primer/what/)
2. [How does the OCDS work?](https://standard.open-contracting.org/latest/en/primer/how/)”
3. [How is OCDS data published?](https://standard.open-contracting.org/latest/en/primer/releases_and_records/)

On the homepage we can update the text on the [homepage](https://data.open-contracting.org/en/), with the links 1 and 3 as shown.

----

### **Data by country**
We've designed the Data Registry to help you find and access public procurement datasets that are available in the [OCDS format](https://standard.open-contracting.org/latest/en/primer/what/). 

Currently, you can access data from over 50 publishers from around the world as **compiled releases** with the latest value of each field. [Learn about how OCDS data is published](https://standard.open-contracting.org/latest/en/primer/releases_and_records/).

----

On the Data detials page ([example](https://data.open-contracting.org/en/publication/17)) we can add a sentence at the top of the section "Data available" with the following text: 

"An individual contracting process has several different stages: tendering, awarding, contracting and implementation. You can dive into the details of the contracting stages in [this tutorial](https://standard.open-contracting.org/latest/en/primer/how/)."

**Comment by jpmckinney** [comment]
@yolile Can you coordinate the translation and implement this issue?

**Comment by yolile** [comment]
The first part looks like this:
![image](https://user-images.githubusercontent.com/6834122/202704704-1522e50b-2807-4798-82c9-26639a8fbb77.png)

But for the details page, I'm not sure exactly where I should put the new text. I'm doing this:
![image](https://user-images.githubusercontent.com/6834122/202704814-258b1b69-3e0f-4c94-9d43-61ae4d967f74.png)

But @sabahfromlondon, could you please help me indicating how and where exactly should I put the new text? Thanks!

**Comment by sabahfromlondon** [comment]
Hi @yolile the first part is perfect.

The second part I was thinking a sentence going across the page like this:
<img width="473" alt="image" src="https://user-images.githubusercontent.com/11212467/202707463-eb0891c8-8b80-41b9-83d7-7508ec4ac9d0.png">

**Comment by yolile** [comment]
Perfect, thank you!
