### ISSUE TITLE
Data for Uganda not available in Data Regsitry

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#259]
A user commented that data for Uganda is missing.

Checking the regsitry, there is no dataset for that country: https://data.open-contracting.org/en/search/?letter=U

Unsure if there is a reason or if it was accidently omitted.

**Comment by yolile** [comment]
Thank you for reporting! The OCDS publication from Uganda has been down since before the registry was launched, so it is not in the registry https://github.com/open-contracting/kingfisher-collect/issues/837.

**Comment by sabahfromlondon** [comment]
Ok thanks good to know. I will feed that back to the user who flagged this. 

Is it not possible to publish the data we accessed before the publication went down? We have done this for other datasets.

**Comment by jpmckinney** [comment]
We don't have a copy for Uganda, so we can't.

**Comment by jpmckinney** [comment]
If we think it's relevant to have pages for data that is not available, we can re-open #227

**Comment by yolile** [comment]
@sabahfromlondon Uganda is publishing OCDS data again so that we will add them to the registry soon.

**Comment by sabahfromlondon** [comment]
@yolile Fab, thanks for letting me know.

**Comment by yolile** [comment]
@sabahfromlondon Uganda is now in the registry
