### ISSUE TITLE
User request to add datasets to registry

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#261]
The following datasets were highlighted to us by a user that are not currently available in the Data Registry. We shoud investigate if we can and should add these:

- The OCDS databases of Compranet generated by Secretaría de Hacienda y Crédito Público: https://datos.gob.mx/busca/dataset/concentrado-de-contrataciones-abiertas-de-la-apf
- El Sistema de información pública de contrataciones developed by la Secretaría Ejecutiva del Sistema Nacional Anticorrupción available in Plataforma Digital Nacional: https://www.plataformadigitalnacional.org/ 
- This dataset from Mexico includes corruption risk indicators, some of which are constructed with OCDS apparently. At the bottom there is a button to download the procurement data from 2018-2021: https://imco.org.mx/riesgosdecorrupcion/

**Comment by yolile** [comment]
> The OCDS databases of Compranet generated by Secretaría de Hacienda y Crédito Público: https://datos.gob.mx/busca/dataset/concentrado-de-contrataciones-abiertas-de-la-apf

All of the links listed there return 404, I reported this issue with the partner now.

> El Sistema de información pública de contrataciones developed by la Secretaría Ejecutiva del Sistema Nacional Anticorrupción available in Plataforma Digital Nacional: https://www.plataformadigitalnacional.org/

As far as I know, they are republishers of the Compranet publication, and in fact, the "Descarga todos los datos { JSON }" section at https://www.plataformadigitalnacional.org/contrataciones redirects to https://datos.gob.mx/busca/dataset/concentrado-de-contrataciones-abiertas-de-la-apf. I guess we could still add them, saying that they are republishers. 

> At the bottom there is a button to download the procurement data from 2018-2021: https://imco.org.mx/riesgosdecorrupcion/

Ah, but not in OCDS format, I'm afraid.

**Comment by sabahfromlondon** [comment]
Thanks @yolile! I will feed this back to the person who shared the links. 

I'm not keen on adding re-published data either. Do we know if the re-publisher has done any transformation on the data to add value? If not, I don't see the point of adding it.

**Comment by yolile** [comment]
> I'm not keen on adding re-published data either. Do we know if the re-publisher has done any transformation on the data to add value? If not, I don't see the point of adding it.

Hmm, actually, I see that they include two publications, one for Compranet and another one for "Secretaría Ejecutiva del Sistema Estatal Anticorrupción de Aguascalientes" which "original" publication I can't find anywhere else, so maybe we can add them. A question is if we want to add one entry for their Compranet publication and another one for the Aguascalientes publication or if we want just one entry for both, under "Plataforma Digital Nacional". I believe they will add other (re)publications over time, so not sure if we want to keep each of them separated or altogether. @jpmckinney this is also relevant for how we update their Kingfisher Collect spider.

**Comment by jpmckinney** [comment]
We can defer to https://github.com/open-contracting/kingfisher-collect/issues/976, as Collect is the gateway for publications to be added to the registry.
