### ISSUE TITLE
Update relevant resources to refer to Data Registry

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#271]
- [x] Kingfisher Collect ReadTheDocs

Data use tutorials

* [x] https://www.open-contracting.org/resources/learning-lab-getting-exploring-ocds-data-with-google-sheets-beta/
* [x] https://www.open-contracting.org/resources/learning-lab-advanced-ocds-analysis-with-excel-beta/
* [x] https://www.open-contracting.org/resources/accessing-ocds-data-notebook-for-advanced-users/
* [x] https://www.open-contracting.org/resources/flatten-tool-colab-notebook-for-non-technical-users/

**Comment by jpmckinney** [comment]
@camilamila @yolile Can you check whether any of the data use tutorials ought to be updated to refer to the data registry? https://www.open-contracting.org/resources/?tab=learning-library&learning-resource-category=use

**Comment by yolile** [comment]
Hmm, there are some of them that are about using OCDS in a tabular format. That tabular format is the current flatten tool format. Do we want to update those resources to refer to flatterer format?

**Comment by jpmckinney** [comment]
We can, but that's maybe a separate issue.

Don't our materials have a step like "get OCDS data"? In any case, getting OCDS data is necessary for any use, so we should have at least one sentence pointing people to the registry.

I thought I remembered some materials that used Kingfisher Collect directly. We should add a sentence pointing people to the registry (we can still keep the Collect content, but it's for more advanced needs).

**Comment by yolile** [comment]
Yes, but then the guidance uses the "flatten tool" format for exploring/using the dataset, so for example, if I'm following the guidance, download the data from the registry, and want to go to the next step in the guidance the format won't be the same as the data I downloaded. I guess we could say something about the different format in the same little box.

**Comment by jpmckinney** [comment]
For the other issue about flatterer, we can add a link to the Google Doc at https://www.open-contracting.org/resources/flatten-and-unflatten-ocds-data-notebook/

Where do you want to track those issues – in the CRM or an issue-only GitHub repository?

**Comment by jpmckinney** [comment]
> Yes, but then the guidance uses the "flatten tool" format for exploring/using the dataset, so for example, if I'm following the guidance, download the data from the registry, and want to go to the next step in the guidance the format won't be the same as the data I downloaded. I guess we could say something about the different format in the same little box.

Aha, yes, we can make a note like:

> If a publisher only offers JSON files, use the [OCP Data Registry](https://data.open-contracting.org/) to access all OCDS datasets worldwide. The Excel files from the Data Registry may have different column names and sheet names than those in this tutorial.

**Comment by yolile** [comment]
I've updated all the resources now
