### ISSUE TITLE
Use better detailed flags

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#286]
See svg-flags branch.

We mainly need to migrate the `country_flag` field to the new file names, then can deploy.

**Comment by yolile** [comment]
Implemented, migrated and deployed in #287, but now the flags are not well aligned, I will make an additional commit to fix that

![image](https://user-images.githubusercontent.com/6834122/224325657-56102a92-13e9-4239-a57f-705f30432998.png)

**Comment by yolile** [comment]
Fixed in https://github.com/open-contracting/data-registry/commit/989079dceb01c195564d9608aa16f22ec909636c, but now Nepal is not looking good. The new images have different sizes than the previous ones, so I'm not sure what is the best solution for this
