### ISSUE TITLE
`collection.last_update` is being set before new data is ready

### ISSUE THREAD

**Issue by yolile** [open-contracting/data-registry#290]
Currently, we update the new `collection.last_update` field as soon as the collect task is done
https://github.com/open-contracting/data-registry/blob/920e0f5d2ee055fe5b8b11ffe8938451ff1ad1b6/data_registry/process_manager/task/collect.py#L59

However, the new updated data is only shown in the registry after completing all the other tasks (process, pelican, export, flattener). For small datasets, this is not a problem, but for big ones, that takes longer to be ready (or even if some tasks fail), then the information in the registry is incorrect. For example, the new collection process for Ecuador started today. However, the data is still from the last collection (November 2022)

![image](https://github.com/open-contracting/data-registry/assets/6834122/3aa7ec04-5e79-49ff-afec-096099ee15be)

This could cause some confusion, e.g., I could assume Ecuador is not updating its data since November, which is not true.

I think we should only update the `collection.last_update` field when all jobs have been finished.

**Comment by jpmckinney** [comment]
Yes, makes sense to me!

**Comment by yolile** [comment]
Ah, closing as the issue was reported already at #106
