### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#3]
We haven't discuss internationalization of the web site. There are 2 questions
- will we translate the website into multiple languages? I see OCP's website is in EN, ES and RU
- if so, ho will we handle manually added information. Currently I see `Data quality summary` text and highlighted `Data quality issues`. Should we have an option to insert it in 3 (or more/less) languages?

**Comment by jpmckinney** [comment]
1. Yes, we will translate it to at least Spanish.
2. We should have some generic solution. For now I found https://pypi.org/project/django-modeltranslation/ but there are many projects on PyPi (some are old and maybe out-of-date).

**Comment by jakubkrafka** [comment]
Let's leave technical solutions behind for a while (django-modeltranslations is definitely a great candidate)
There will be two types of translations:
1. static texts - this can be easily translated, the support for almost every language will be available (including date/number formats etc.), of course. But, will be the flatten tool compatible? Rather double checking here.  
2. dynamic content - must be translated/entered each and every time. Will be the maintainers capable, and most importantly willing to:), to fill these texts in all available languages? My question is based on past experience, where everything was translatable, but in reality, the pages were missing the majority of texts in the non-primary languages.

**Comment by jpmckinney** [comment]
1. I'm not clear what issue you're anticipating with the flatten tool. Can you explain in more detail?
2. We will likely only do Spanish, for which we have many available translators, and many staff who can write in both English and Spanish. Latin America has the most OCDS publishers, so we are incentivized to dedicate the resources. That said, the system should fallback to English and not break if the Spanish text isn't available. Alternately, we can consider whether an object is considered invalid unless it is fully translated.

**Comment by jakubkrafka** [comment]
1. flatten tool should be able to take over in selected language -> there should be an option how to hand over language to flatten tool GUI (browser language is not an option here, user-selected language differs from default browser language a lot)
2. I like the option B - not published until translated

**Comment by jpmckinney** [comment]
1. We'll need to pass arguments to the flatten tool (e.g. the dataset to flatten) so we can set the language among those arguments (whether query string parameters or otherwise).
1. We can start with option B then.

**Comment by hrubyjan** [comment]
new development requirement #41 based on this discussion
