### ISSUE TITLE
Acceptance criteria - Pelican

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#31]
At the end of each phase of data processing we should evaluate whether it ended well, there is something suspicious or this particular phase failed. 
For `pelican` phase define criteria that will 
a) prevent a dataset from being published in data registry
- we shouldn't be too defensive and try to detect obvious problems

b) raise a warning but will not prevent dataset from being published
- this should serve to notify admin that there is some issue worth inspecting

**We should not insist on having some criteria if we will not see some meaningful rules**

**Comment by jpmckinney** [comment]
On the call, I forget what we said, but I seem to remember thinking that even if Pelican fails completely, then as long as the earlier steps passed, then it should not go to a "failed" state per #32.

**Comment by jpmckinney** [comment]
No additional work needed. Pelican is currently robust enough to always succeed on field-level coverage checks. There are open issues to make it more robust on other checks – but we don't currently run those / use their results in the registry.
