### ISSUE TITLE
Merge the rest of the exporter app into the data_registry app

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#315]
Started in #314

**Comment by yolile** [comment]
Note that I had to restore "exporter" as an app https://github.com/open-contracting/data-registry/commit/4c6c5b277ce00d6f441231028476199c87709438 otherwise the exporter related commands weren't accessible

**Comment by jpmckinney** [comment]
Thanks! Did Docker Compose show any useful output, when it attempted to start a missing command? Just checking whether we can change anything to be notified of such issues in future.

**Comment by yolile** [comment]
Yes, a lot of:
````
Unknown command: 'exporter'
Type 'manage.py help' for usage.
````

for exporter, flattener, and wiper.

**Comment by jpmckinney** [comment]
Actually the division seems fine, and somewhat useful. The only times we break encapsulation are:

- views (to get Export class)
- exporter and flattener tasks (this is just to not repeat RabbitMQ helpers in the data registry app)

If we were to merge the apps, the only simplification is that we wouldn't need `exporter.util.TaskStatus`.
