### ISSUE TITLE
Implement new publication description guidance re: linked datasets

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#332]
See https://docs.google.com/document/d/1Pr87zDrs9YY7BEvr_e6QjOy0gexs06dU9ES2_-V7Lzw/edit#bookmark=id.zg938z7lisp8

**Comment by jpmckinney** [comment]
The above link goes to:

> Discuss in one or more paragraphs the coverage in terms of:
>
> …
>
> * Other relevant datasets
>   * Check whether the publication policy fills in the _Links to relevant datasets_ section and/or ask the program manager.

So, I think my meaning in the issue title is to mention related datasets in the publication description.

**Comment by jpmckinney** [comment]
@yolile Who should take this one? Should we assign publications to team members by region?

**Comment by yolile** [comment]
Hmm, do we still want to do this as we are now going to provide a direct link to the publication policy which already contains this information?

**Comment by jpmckinney** [comment]
I don't think many users will be clicking through to the publication policy, so it depends on how much we want to prioritize this use case (of easily discovering linked datasets).

**Comment by yolile** [comment]
Correct, but even most of the data users (that contact us at least) don't read the existing descriptions, so I'm not sure if they will read the info about linked datasets there either.

**Comment by jpmckinney** [comment]
Ok, closing as not a priority.
