### ISSUE TITLE
Check temporary data collection issues

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#348]
e.g. after a week, in case there's a temporary IP ban or similar. These are currently frozen until issue is resolved.

* [ ] https://contrataciones.gov.py/datos/api/v3/doc/oauth/token DNSLookupError from server, but not locally.
  * Note: In Sentry, can filter these out with `!title:"DNSLookupError: DNS lookup failed: no results for hostname lookup: contrataciones.gov.py."` or `!title:"Gave up retrying <POST https://contrataciones.gov.py/datos/api/v3/doc/oauth/token> (failed 3 time..."`, depending on the issue.
* We also witnessed `title:"DNSLookupError: DNS lookup failed: no results for hostname lookup: nocopo.bpp.gov.ng."` but nigeria_portal succeeded more recently. In another issue, saw the corresponding `title:"Gave up retrying <GET https://nocopo.bpp.gov.ng/ocdsjson.ashx?ocid=all> (failed 3 times): DNSLook..."`

The following are not temporary:

* https://github.com/open-contracting/kingfisher-collect/issues/1045
* https://github.com/open-contracting/kingfisher-collect/issues/1037
* https://github.com/open-contracting/kingfisher-collect/issues/1022
* https://github.com/open-contracting/kingfisher-collect/issues/1083

**Comment by yolile** [comment]
The same issue was seen for Uruguay Retrying `<GET http://comprasestatales.gub.uy/ocds/rss/2024/04> (failed 1 times): DNS lookup failed: no results for hostname lookup: comprasestatales.gub.uy.` but then it worked again

**Comment by yolile** [comment]
Buenos Aires returned 503 https://data.buenosaires.gob.ar/api/3/action/package_show?id=buenos-aires-compras but it is working locally on the server

**Comment by yolile** [comment]
`canada_montreal` returned 520 but it is working on the server https://ville.montreal.qc.ca/vuesurlescontrats/api/releases.json?limit=10000

**Comment by yolile** [comment]
>  https://contrataciones.gov.py/datos/api/v3/doc/oauth/token DNSLookupError from server, but not locally.

I get `curl: (6) Could not resolve host: contrataciones.gov.py` in the server

**Comment by jpmckinney** [comment]
`dig contrataciones.gov.py` and `nslookup contrataciones.gov.py` also fail from the data support server (ocp23), but not from Linode. So, it's like an IP block is banned.

For Montreal, the data support server can collect it:

    curl -n https://collect.kingfisher.open-contracting.org/schedule.json -d project=kingfisher -d spider=canada_montreal -d note="Started by James." -d steps=

**Comment by jpmckinney** [comment]
I'm proxying Montreal now and it works. I unfroze it.

Not sure why you froze Buenos Aires. I now set `validate_json = True`, because it returns incomplete JSON. https://github.com/open-contracting/kingfisher-collect/issues/874

**Comment by yolile** [comment]
Because Buenos Aires has only one file and it is broken

**Comment by jpmckinney** [comment]
Closing here as now a deployment issue with Bob.
