### ISSUE TITLE
Document reason for freezing a publication

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#353]
Can discuss in this issue first.

We can also consider adding a note (with a date) in the admin when freezing a publication.

**Comment by yolile** [comment]
The current criteria are:
- The source data is broken/not available
- The source data is not being updated anymore

**Comment by jpmckinney** [comment]
Ok, added criteria to docs:

> A publication is frozen if:
>
> -  The spider is removed from Kingfisher Collect. The publication is never unfrozen.
> -  The source is temporarily broken or otherwise unavailable. The publication is unfrozen when the source is fixed.

I think it might be useful to track temporary freezes via the admin, as right now we would need to compare to Collect issues to figure out why something is frozen.

**Comment by yolile** [comment]
> Ok, added criteria to docs:

I think that we are missing one criterion, that is when the source is not broken and it is still available but is not updated with new data anymore (my second bullet)

> I think it might be useful to track temporary freezes via the admin

Agree, we should add a note with a date as you suggested

**Comment by jpmckinney** [comment]
> I think that we are missing one criterion, that is when the source is not broken and it is still available but is not updated with new data anymore (my second bullet)

Aha, but in that case, don't we set retrieval frequency to `NEVER`? We don't need to freeze those.

**Comment by jpmckinney** [comment]
> > I think that we are missing one criterion, that is when the source is not broken and it is still available but is not updated with new data anymore (my second bullet)
> 
> Aha, but in that case, don't we set retrieval frequency to `NEVER`? We don't need to freeze those.

I unfroze those with retrieval frequency of `NEVER`, since they will not be scheduled already.

**Comment by jpmckinney** [comment]
Ok, I updated `scrapy checkall` in Kingfisher Collect to report whether a collection is frozen but has no issues (or vice versa). Since we now have a way to audit/understand frozen collections, this issue is resolved.
