### ISSUE TITLE
Get list of sources from Collect

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#36]
For scheduling purposes we need to get a list of sources from Collect so that admin can select the source which should be processed by data registry

**Comment by jpmckinney** [comment]
You can use this API: https://collect.kingfisher.open-contracting.org/listspiders.json?project=kingfisher

I can share the basic authentication.

**Comment by jpmckinney** [comment]
In Python, you can do something like:

```python
from scrapy.crawler import CrawlerProcess
from kingfisher_scrapy import settings

runner = CrawlerProcess(settings=settings)
runner.spider_loader.list()
```

**Comment by t-mrazek** [comment]
implemented
