### ISSUE TITLE
Consider adding a filter by access method type

### ISSUE THREAD

**Issue by yolile** [open-contracting/data-registry#361]
A user wanted to know which publishers have an API so that he could develop tools consuming them. We could add a field and later a filter to search by access method, e.g. API or bulk download

**Comment by jpmckinney** [comment]
I guess for now you pointed the user to Kingfisher Collect's docs?

**Comment by yolile** [comment]
I pointed him to the data registry itself first (he didn't come from there and he also asked about who publishes real-time or near real-time data, and we have a filter for that in the registry) and then filtered the list of publishers who have an API for him and yes, also shared Kingfisher Collect docs and code for reference

**Comment by jpmckinney** [comment]
I'm not sure that this belongs in the registry. The registry is ultimately about downloading data. This user just wants to know which sources have APIs, and doesn't want to download data from the registry. That's not information we catalog in the registry (we often prefer bulk sources as they are faster when downloading everything).

I think this is out-of-scope, but we can consider e.g. improving the updatedocs command in Kingfisher Collect, to generate a page that lists bulk vs API spiders. Now that the Registry has an API, we could even write some JS in Collect's docs that links to (or renders information from) the Registry.

I'll let you create the issue in Collect, if you think this need is not a one-time request.
