### ISSUE TITLE
Rich text

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#37]
For some paragraphs like long description of dataset or notable features beyond the core OCDS we need to be able to publish rich texts (bold, bullets, ...)

Integrate some solution (e.g. https://pypi.org/project/markdown-it-py/ or https://pypi.org/project/django-markdown/ or https://pypi.org/project/django-richtextfield/) which we can use with Django admin for editing long texts

**Comment by t-mrazek** [comment]
implemented, django-markdownx

**Comment by jpmckinney** [comment]
Hmm, I am concerned about django-markdownx's maintenance. There is no release since 2019, and it has warnings with Django 4.0.

I think just a plain textarea that is rendered with markdown-it-py (very well maintained) is enough. We don't need a live preview (it's a nice-to-have).

**Comment by jpmckinney** [comment]
Also, are we really using all these Markdown extensions? https://github.com/open-contracting/data-registry/blob/1ab63c4c8a397b8999bf4d1b11a83c3fec0d8972/core/settings/base.py#L127-L135

I'd rather not use python-markdown or pymdown-extensions. All our other tools use markdown-it-py.
