### ISSUE TITLE
Exporter

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#38]
Design and implement component that will take all data for a given collection and prepares yearly dumps and one full dump which we will offer for download from the Data access section

Dumps will be new line delimited files. One compiled release per one line so that user can process the file line by line.

Let's have two level directory structure
- create one directory per one collection (data source) 
- and one subdirectory per each job for which we create the dumps.

**Comment by t-mrazek** [comment]
full and annual dumps exporter implemented

**Comment by hrubyjan** [comment]
done for now refactor and improvements will be needed when integration with flatten tool is agreed. But I'll start a new issue for this.
