### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#4]
Implement landing page of the Data registry
Detailed designs will be available in Zeplin
Links in a footer are identical with the corresponding links from https://www.open-contracting.org/

![image](https://user-images.githubusercontent.com/17906453/108673467-03cc0580-74e4-11eb-902f-d1b231693d0c.png)

**Comment by jpmckinney** [comment]
Would "Open Contracting Data Registry" fit instead of "OCP Data Registry"?

**Comment by hrubyjan** [comment]
No problem
