### ISSUE TITLE
First letter filter modifications

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#40]
- Highlight letters which will provide some datasets (purple underscored)
- Highlight active filter (bold in circle)
- Add option to clear filter (crossed funnel icon and `Clear` label)

![image](https://user-images.githubusercontent.com/17906453/117931508-8d2eef00-b2ff-11eb-9e1c-0e9365072188.png)

**Comment by t-mrazek** [comment]
implemented
