### ISSUE TITLE
Get data availability results from Pelican

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#42]
For each count information we can take the value from Pelican. It's stored in Pelican as a number of isSet check for a subfield of a particular structure.

For example here we know that there is 3601 `awards` because we checked the presence of `awards.id` 3601x
![image](https://user-images.githubusercontent.com/17906453/118621976-2ad66280-b7c7-11eb-9811-cce42bfbee70.png)

The information we need is result of `isSet` check for the specific path which will be mention for each item
![image](https://user-images.githubusercontent.com/17906453/118622212-640ed280-b7c7-11eb-9757-4645fe394f41.png)

List of available data

**Parties**
Count of parties - result of `parties.id` isSet check

**Planning**
Count of planning activities  - result of `planning.budget` isSet check (plannings does not have ids 🤷‍♂️ )

**Tenders**
Count of tenders - result of `tender.id` isSet check
Count of tenderers - result of `tenderers.id` isSet check
Count of tender items - result of `tender.items.id` isSet check

**Awards**
Count of awards - result of `awards.id` isSet check
Count of award items - result of `awards.items.id` isSet check
Count of awards suppliers - result of `awards.suppliers.id` isSet check

**Contracts**
Count of contracts - result of `contracts.id` isSet check
Count of contract items - result of `contracts.items.id` isSet check
Count of contract implementation transactions - result of `contracts.implementation.transactions.id` isSet check

**Documents**
Count of documents related to the different stages of the contracting process

Total sum of following counts
- planning.documents - result of `planning.documents.id` isSet check
- tender.documents - result of `tender.documents.id` isSet check
- awards.documents - result of `awards.documents.id` isSet check
- contracts.documents - result of `contracts.documents.id` isSet check
- contracts.implementation.documents - result of `contracts.implementation.documents.id` isSet check

**Milestones**
Count of milestones related to the different stages of the contracting process

Total sum of following counts
- planning.milestones - result of `planning.milestones.id` isSet check
- tender.milestones - result of `tender.milestones.id` isSet check
- contracts.milestones - result of `contracts.milestones.id` isSet check
- contracts.implementation.milestones - result of `contracts.implementation.milestones.id` isSet check

**Amendments**
Count of amendments related to the different stages of the contracting process

Total sum of following counts
- tender.amendments - result of `tender.amendments.id` isSet check
- awards.amendments - result of `awards.amendments.id` isSet check
- contract.amendments - result of `contract.amendments.id` isSet check

**Comment by sabahfromlondon** [comment]
Looks good :)

**Comment by t-mrazek** [comment]
<pelican_domain>/api/dataset_availability/<dataset_id> enpoint added

**Comment by hrubyjan** [comment]
@t-mrazek then done?

**Comment by t-mrazek** [comment]
done
