### ISSUE TITLE
Design - offer yearly and one complete JSON dump

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#43]
Access JSON data should offer to the user
* yearly dumps
* one complete dump

We don't have design for this yet
![image](https://user-images.githubusercontent.com/17906453/118948840-f692ab80-b958-11eb-934f-15153c00a9a2.png)

**Comment by sabahfromlondon** [comment]
Can you clarify the yearly dumps? If a user selects the date range of 3 years, I don't see why we would give them yearly dumps. Sorry if I've missed something

**Comment by hrubyjan** [comment]
That is what we've discussed. This will be a static content no matter what filters user set

Originally we said that the JSON are not the primary format that user looks for, therefore, we will only provide a complete dataset as a JSON dump. But then we said that we can be more user friendly and also prepare yearly dumps so that user does not necessarily download data from 1990 if he/she is only interested in past few years.

Here we will prepare static dumps that won't change. Not a dynamically generated content that will take time to prepare when user selects a date range.

**Comment by hrubyjan** [comment]
![image](https://user-images.githubusercontent.com/17906453/119529604-8a61de80-bd82-11eb-9c9c-3d47fe2bc7eb.png)
