### ISSUE TITLE
Design - Feedback form

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#44]
This form is linked from the data source detail, therefore, url of data source is not needed. We should repeat the name so that user knows to which data source he/she provides the  feedback

Then let user select a type of feedback and then the feedback itself

This does not need to be a standalone page but it can be an overlay

![image](https://user-images.githubusercontent.com/17906453/118952108-f34cef00-b95b-11eb-97a3-040a706bd5f1.png)

**Comment by sabahfromlondon** [comment]
Yes sounds good, can you just clarify the last bit? => _"This does not need to be a standalone page but it can be an overlay"_

**Comment by hrubyjan** [comment]
Like this. Not a page but a "pop up" window. 

![image](https://user-images.githubusercontent.com/17906453/118970335-63647080-b96e-11eb-9a6d-b63e2e812d74.png)

**Comment by hrubyjan** [comment]
@sabahfromlondon do you have a list of feedback Types?

**Comment by sabahfromlondon** [comment]
Oh a pop-up, I see. Looks good! 

Here's the list for the drop down:

Broken link
Incorrect metadata
New data quality issue found
Advice for users of this data source
Other
