### ISSUE TITLE
Collection metadata from Pelican

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#49]
This select to Pelican's DB
```
select jsonb_pretty(meta->'collection_metadata') from production.dataset;
```

will return metadata needed for the collection in data registry

```
{                                                                                
     "url": "The URL where the data can be downloaded isn't presently available.",
     "publisher": "Zambia Public Procurement Authority",                          
     "extensions": [                                                              
     ],                                                                           
     "ocid_prefix": "ocds-23g63a",                                                
     "data_license": "https://www.zppa.org.zm/ocds-license",                      
     "published_to": "2021-05-21 14.48.51",                                       
     "published_from": "2016-08-05 12.14.11",                                     
     "publication_policy": "https://www.zppa.org.zm/ocds-publication-policy"      
 }
```

Get this data from Pelican's API and set it for a particular collection in data registry

Data date range - `published_from` - `published_to`
License (the information we extract, then there will be a relation to a license catalogue)- `data_license`
OCID prefix - `ocid_prefix`

We'll need to fix the way how Pelican get's the data because this is currently broken. It depends on existence of all three type of collection - `original`, `upgraded`, `compiled`. There does not need to be the `upgraded` one which causes the `join` query in DQT returns empty result and we don't get the metadata eventually.

**Comment by t-mrazek** [comment]
Basic endpoint dataset_metadata/<dataset_id> on pelican added + data-registry collection ocds fields update on postprocessing of completed collection.

**Comment by t-mrazek** [comment]
pelican metadata aggregation process fixed
