### ISSUE TITLE
OCID extracted from Pelican but not displayed on collection detail

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#51]
I can see the `OCID prefix` in administration but don't see it on a dataset detail

![image](https://user-images.githubusercontent.com/17906453/120154955-acc78200-c1f0-11eb-906f-094c48f327de.png)

![image](https://user-images.githubusercontent.com/17906453/120155002-b94bda80-c1f0-11eb-8c4c-6d899586bf39.png)

**Comment by t-mrazek** [comment]
fixed
