### ISSUE TITLE
Country information

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#52]
- Where will we display the country information and how will the dataset title look like?
  - country name is currently part of the dataset title. In this case `Spain` is country and `Zaragoza` is a title of the dataset. Will we have titles for all datasets? Because now I see collections like `Moldova`, `Colombia` and we also have a lot of `Digiwhist` collections that only differs in country but don't have special title. 
![image](https://user-images.githubusercontent.com/17906453/120171361-42b7d880-c202-11eb-8fd5-651e9050aa7f.png)

- We'll have bilingual application (EN + ES). How should work the `Country starting with` filter? In english version Spain should be selected by clicking `S` but in Spanish version it should be selected by clicking `E` for Espana?

**Comment by sabahfromlondon** [comment]
@hrubyjan I think we should have titles for all datasets. For instance `Spain Zaragoza` and `Spain Digiwhist`. 

Would it be possible to get a list of all the datasets? I can then draft what all the titles could be and maybe @jpmckinney can sign off.

On the bilingual issue, yes the user will need to select `S` for Spain when in English and `E` for Espana when in Spanish.

**Comment by yolile** [comment]
@hrubyjan you can find the titles as well in the document that I shared in #54

**Comment by jpmckinney** [comment]
https://docs.google.com/spreadsheets/d/1SiGQ78mRaEmG7OKRSs-cHd2RV2Ra-UOLK_qLSkijUec/edit#gid=0 has a mapping between spider names (the "Spider" column to the far right) and the publisher names that OCP uses in its reports. We might change the publisher names for the registry (especially if they are very long), but it is a starting point. Let me know if you need access to the document.

**Comment by hrubyjan** [comment]
Yes, please share it with me. thank you.

**Comment by jpmckinney** [comment]
Done!
