### ISSUE TITLE
Sample descriptions

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#54]
It would be good to have sample texts for let's say 3 datasets so that we can see how the frontend looks like with the real texts

- description
- description long
- data quality summary
- additional data (anything on top of basic OCDS)
- issues found

**Comment by yolile** [comment]
@hrubyjan you can find the draft document with the draft description, description long, and additional data for each publisher in [this](https://docs.google.com/document/d/1Pr87zDrs9YY7BEvr_e6QjOy0gexs06dU9ES2_-V7Lzw/edit#heading=h.yazt77nhe8a4) document.

**Comment by jpmckinney** [comment]
@hrubyjan Paraguay is done. We haven't yet reviewed the others, but I think they are close to what the final text will be.

**Comment by hrubyjan** [comment]
I don't mind if it's not reviewed. I only needed something close to the final version so that I can se how long and how structured the texts will eventually be and whether it somehow affects the design. You know, sometimes you can draw nice picture with a  this long description but if it is in reality thiiiiiiis long then the picture is ugly :)
