### ISSUE TITLE
User tracking

### ISSUE THREAD

**Issue by jakubkrafka** [open-contracting/data-registry#6]
I guess that user tracking (i.e. Google Analytics, Google Tag Manager) will be part of the application. Please could you provide more specific details to integrate those? Thanks!

**Comment by jpmckinney** [comment]
As mentioned in #7, it'll be Fathom. You can put this in the `head`:

```html
<script src="https://cdn.usefathom.com/script.js" data-site="HTTGFPYH" defer></script>
```

To ignore requests from development, I usually change it to:

```html
<script src="https://cdn.usefathom.com/script.js" data-site="HTTGFPYH" defer data-excluded-domains="127.0.0.1,0.0.0.0"></script>
```

**Comment by jakubkrafka** [comment]
Thanks! I like it configurable. There is variable FATHOM_KEY in settings, when set, the analytics will start to work.

**Comment by jpmckinney** [comment]
Note: In Toucan (a Django project) we also have a setting for the custom domain. https://github.com/open-contracting/toucan/blob/main/ocdstoucan/settings.py#L165-L166

Many paranoid browser extensions like uBlock Origin block Fathom, even though it doesn't track users, serve ads, etc. To get around blockers, we use a custom domain.

**Comment by jpmckinney** [comment]
I've updated the code snippet to use our custom domain, and to add another excluded domain.

**Comment by jakubkrafka** [comment]
Good tip, thanks! Integrated as well.
