### ISSUE TITLE
Compress JSON files using GZ

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#61]
@sabahfromlondon also wrote on Slack that simple instructions should be included (mainly for Windows users, since GZ is natively supported on macOS and most Linux/Unix systems).

**Comment by hrubyjan** [comment]
I guess this form can also contain the explanation text
![image](https://user-images.githubusercontent.com/17906453/122365715-34382380-cf5b-11eb-987a-5fcda969a529.png)

@sabahfromlondon please think about it when doing the copywriting. Thank you

**Comment by sabahfromlondon** [comment]
Updated copy:

### Access JSON Data

Select the time period that you would like to access JSON data for. 

**All time data from this source**
This file will contain OCDS data for all fields provided by the publisher and for the entire time period for which data has been made available by the publisher. Please note that the file may be extremely large and may take some time to process.

**Data by year**
This file will contain OCDS data for all fields provided by the publisher, but only for the year selected below. Depending on the source, the file may be extremely large and may take some time to process.

**Comment by jakubkrafka** [comment]
Done and deployed.
