### ISSUE TITLE
Decide when to build Docker containers (e.g. tag vs commit)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#62]
For example:

https://github.com/open-contracting/spoonbill-web/blob/main/.github/workflows/push.yaml
https://github.com/open-contracting/spoonbill-web/blob/main/docker-compose.deploy.yaml

**Comment by jpmckinney** [comment]
If we decide not to use tags, I'll delete all the tags in the other repos (pelican-frontend, pelican-backend, kingfisher-process, kingfisher-collect) to avoid confusing future developers.

**Comment by jakubkrafka** [comment]
As with everything, this is up to your taste and current needs. Thinking aloud about tag advantages:
1) "should be deployable" and "is deployable" are in a real world quite different things:) (we don't have to go far i.e. last change where users weren't able to login into the admin interface and have been practically cut out. In theory, everything was deployable) 
2) tags allow you to easily return to the older version in case of "something is broken" (each build tags image with :latest and :tag_version tags)
3) tags allow you to easily deploy staging/test environments
4) aligned tags can be used to sync versions in multi-component environments (i.e. data-registry needs a special version of kingfisher-process)

On the other side:
Tags are too complicated a too heavy for our current needs.

All the arguments are relevant to me, but I'm not able to decide as I'm not in your shoes. With tags (and few rules behind those), you can easily achieve a very robust development/production infrastructure. But, maybe it's not a real need, just overengineering.

**Comment by jpmckinney** [comment]
I think we can maybe go somewhere in the middle. Instead of tagging for *each* build (which is just extra work across multiple repositories), we discussed:

1. Building to a different Docker tag for non-main branches (e.g. to be able to test a branch in staging). If we use a constant tag (like "develop"), then different branches will clobber each other. We can instead use the branch name as the tag. To clean up old images, we can maybe use https://github.com/bots-house/ghcr-delete-image-action/issues
2. In case we introduce a breaking change on the main branch, we can maybe store a constant in the workflow, so that instead of `latest`, it builds `v1`, and then before a breaking change, we change it to `v2`. That way, in a hypothetical scenario, Process and Pelican can stay on `v1` on the helpdesk server, but change to `v2` for the data registry.

The example in [GitHub's docs](https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages) use [docker/metadata-action](https://github.com/docker/metadata-action), which determines tags/labels automatically based on branches, tags, PRs, etc.

**Comment by jpmckinney** [comment]
Alright, I'll leave this as-is, as it's not so hard to add a tag, and it *might* make some future problems easier.
