### ISSUE TITLE
Exporter revision

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#63]
- we will use GZ to compress dumps created by exporter
- create dumps which will be needed for integration with flatten tool
  - most probably monthly dumps
  - think about whether we need to create monthly and yearly dumps or we can connect monthly dumps when user wants to download yearly dumps
- add more log messages so that we can see the progress of the task because it takes quite a lot of time for large collections
- test the exporter with some large source like `portugal` because it didn't finish with the current version

**Comment by jakubkrafka** [comment]
Done.
