### ISSUE TITLE
Country should be also available in a job list

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#66]
In a admin section please also display country for each job because otherwise I only see a lot of Digiwhists but don't know which dataset exactly

The `collection` here can be the same as on a frontend `country` + `title` 

![image](https://user-images.githubusercontent.com/17906453/122370954-c5a99480-cf5f-11eb-98d1-d8667c646606.png)

**Comment by t-mrazek** [comment]
new table column country added
