### ISSUE TITLE
Allow to open task from a job detail

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#67]
- Here I see that something went wrong with the Task but I cannot directly open the task to see what went wrong. 

![image](https://user-images.githubusercontent.com/17906453/122371626-4cf70800-cf60-11eb-8269-bca84da831de.png)

**Comment by t-mrazek** [comment]
added native Django edit link ("Change" next to task id). 

![Screenshot from 2021-06-21 08-00-10](https://user-images.githubusercontent.com/81358737/122714042-f42cb580-d266-11eb-9ae5-22f9e4157be4.png)
