### ISSUE TITLE
Collection - admin iterface improvements

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#69]
- Make a description field a rich text field. Short `description` also contain links, therefore, we need to make this field rich text field
- get rid of an OCDS label field. This is always static and it contains OCDS on a frontend even when it's empty on a backend
- if it's no big deal then move field, `country`, `update frequency`, `License` + `License custom`, `Summary`, `Additional data`, `Issues` before fields that are filled in automatically (date from, date to, last update, ocid prefix, counts, formats)

**Comment by t-mrazek** [comment]
all tasks done
