### ISSUE TITLE
Cookie policy

### ISSUE THREAD

**Issue by jakubkrafka** [open-contracting/data-registry#7]
In past years, many pages are following https://www.privacypolicies.com/blog/eu-cookie-law/ . Sometimes (depending on the regional legal authority), this leads to annoying, useless cookie banners (in other countries just the page explaining cookie used is considered to be enough). How do you prefer to target this?

**Comment by jpmckinney** [comment]
For web analytics, we'll be using Fathom Analytics. Google Analytics is too much of a privacy hassle. A lot of users block it.

Fathom does not use cookies: https://usefathom.com/compliance

Do we need cookies for the registry itself?

**Comment by jakubkrafka** [comment]
Not obligatory, unless we want to store the selected language for the next time for example.

**Comment by jpmckinney** [comment]
I haven't read https://www.privacypolicies.com/blog/eu-cookie-law/ in detail, but my understanding is that a cookie that just stores a language does not identify the user and is therefore non-personal, and is therefore not covered by GDPR, which is about personal information.

**Comment by jpmckinney** [comment]
For other reasons (like caching), however, it might be a good idea to put the language in the URL, e.g. registry.open-contracting.org/en/, in which case we don't need a cookie at all.

**Comment by jakubkrafka** [comment]
Unfortunately, you are and you are not right:) (There are some obscure national regulators requiring the banner for all cookies:( (Yes, one part is eu-cookie-law and second part is its implementation in particular countries, which differes a lot. I.e. czech regulator does not require the banner at all, well, at least according to some legal opinions)  But I agree, in our case, we can forget on that completely for now.
