### ISSUE TITLE
Visual design changes to homepage

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#72]
@hrubyjan some quick fixes for the homepage of the registry please:

1. The E in Espanol should be capitalised on this and all other pages:
<img width="150" alt="Screenshot 2021-06-17 152930" src="https://user-images.githubusercontent.com/11212467/122416915-0534a880-cf81-11eb-9a42-3603f66de896.png">

2. Can you increase the white space as marked in the image below?
<img width="858" alt="Screenshot 2021-06-17 152958" src="https://user-images.githubusercontent.com/11212467/122417342-4fb62500-cf81-11eb-82f4-33f2ddb3d08a.png">

3. Some spelling errors, but please fix after we have copy edited at our end -

**Data by Country**
The Data Registry has been designed to help you to search for and easily access public procurement from a number of different countries that publish data in the OCDS data standard.

**Learn About The Source**
Information about each country dataset is provided to help you to understand what fields/column headings are available or if there are any documents. Information about each dataset and any known quality issues are provided. 

**Easily Access Data**
You can easily download datasets in JSON or in Excel/CSV by following the steps in the Flatten Tool Interface.

**Comment by sabahfromlondon** [comment]
@georgneu please take a look at the text and feel free to suggest edits

**Comment by hrubyjan** [comment]
@sabahfromlondon looks big enough at my side when trying with the similar resolution. What browser did you use? What device, resolution?

![image](https://user-images.githubusercontent.com/17906453/122673315-20e1be00-d1d0-11eb-8c32-dc0a4fd08d90.png)

**Comment by sabahfromlondon** [comment]
@hrubyjan I checked again and it now looks fine. I assumed it was fixed!
