### ISSUE TITLE
Country info card link to data details pages

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#74]
The "See details" call to action looks too small and on my screen and there is too much empty space.

I also automatically tried to click on the title "Germany Digiwhist" in the example, which is common UX design practice, so think we should hyperlink this too.

![InkedScreenshot 2021-06-17 154927_LI](https://user-images.githubusercontent.com/11212467/122421092-0e734480-cf84-11eb-82b8-19dd2411924a.jpg)

**Comment by sabahfromlondon** [comment]
I also think the text OCDS in the label looks off centre: 

<img width="100" alt="Screenshot 2021-06-17 155342" src="https://user-images.githubusercontent.com/11212467/122421455-48dce180-cf84-11eb-8136-75aabf068ff9.png">

**Comment by hrubyjan** [comment]
Make the whole design narrower so that we get rid of the empty spaces (the is a lot of other ugly empty spaces)

**Comment by t-mrazek** [comment]
The whole box is now clickable and the click redirects to the detail page.

**Comment by t-mrazek** [comment]
The narrower layout was set. The content width doesn't exceed 1400px.

**Comment by sabahfromlondon** [comment]
The narrower layout is much better. Thank you

I actually didn't notice that the box changes colour slightly upon hover. I also missed that the "See details" button gets underlined. It's much better, but if we could also underline the title when the user hovers over the box, the feedback will be much stronger.

The OCDS label I mentioned before is still an issue 



> I also think the text OCDS in the label looks off centre:
> 
> <img alt="Screenshot 2021-06-17 155342" width="100" src="https://user-images.githubusercontent.com/11212467/122421455-48dce180-cf84-11eb-8136-75aabf068ff9.png">

I just checked again and the label is also coming up as a contrast error. Possibly because the spacing between the characters is not great? Can you take a look?

**Comment by hrubyjan** [comment]
@sabahfromlondon actually it now combines two styles. There is the `See details` link which can be combined with the title link. 

The second style is that the whole card is a link (that's why the box changes colour slightly upon hover.). In this case it makes no sense to also have the `See details` link. 

I like the style when I can click the whole box as I don't have to search for links a move to them.
Which one should we apply?

**Comment by sabahfromlondon** [comment]
@hrubyjan You can't not have a call to action button. We need to keep the `see details` button.

I've said before, the different shades of grey for the are not obvious. Someone with a visual impairment will not see the colour change. Nor is it a standard design pattern, so has the potential to cause confusion on it's own. 

I'm perfectly fine with the whole box being clickable. My suggestion is about feedback to the user the something is clickable. It's why I asked for the title to look like a hyperlink upon hover on the box.

**Comment by jpmckinney** [comment]
> It's why I asked for the title to look like a hyperlink upon hover on the box.

Done - a non-color designator (text underline) is added to the heading on hover.

For the other issue mentioned (alignment of "OCDS"), this version of the registry ONLY has OCDS datasets, so I simply removed those badges. As I understand, they had a function when the plan was to include non-OCDS datasets.

**Comment by sabahfromlondon** [comment]
@jpmckinney great thank you! :)

And yes fine to remove the OCDS label for now.
