### ISSUE TITLE
Contrast errors

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#75]
The dark grey text on light a grey background is a contrast error. Suggest we change the grey text to black and bold?

<img width="335" alt="Screenshot 2021-06-17 162545" src="https://user-images.githubusercontent.com/11212467/122427718-416c0700-cf89-11eb-88bc-d8d3cec83606.png">

The grey text on white is also a contrast error. Suggest we have text  formatting the following way? Happy for other  suggestions

**Data date range:** Aug 2020 - Aug 2020

and 

**Parties** 
Count of parties: 8002

<img width="532" alt="Screenshot 2021-06-17 163026" src="https://user-images.githubusercontent.com/11212467/122427886-5ea0d580-cf89-11eb-9b3f-2d9e12ee83aa.png">

**Comment by hrubyjan** [comment]
Please try it and we'll see whether it's nice or not

**Comment by t-mrazek** [comment]
The mentioned grey texts are now in thin font and "black" color. Values are "black" and in regular font. The suggested bold black text is too aggressive by my own opinion and looks ugly. So I tried the thin text and I think it looks better.

**Comment by sabahfromlondon** [comment]
Looks good to me :)

**Comment by jpmckinney** [comment]
Closing as Deployed.
