### ISSUE TITLE
Change order of Data contains options

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#76]
The order should be as follows:

Parties
Planning
Tenders
Awards
Contracts
Documents
Milestones
Amendments

Currently the order is different:

<img width="123" alt="Screenshot 2021-06-17 163829" src="https://user-images.githubusercontent.com/11212467/122429827-fb17a780-cf8a-11eb-88c0-bbabe2b31181.png">

**Comment by t-mrazek** [comment]
order changed

**Comment by sabahfromlondon** [comment]
Looks good, thank you
