### ISSUE TITLE
Last update info

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#79]
Extract the `Last updated` information from kingfisher collect. 
![image](https://user-images.githubusercontent.com/17906453/122673416-a36a7d80-d1d0-11eb-9938-b5e02fec4441.png)

This should be start time of the collect phase
It can be eithet taken from scrapy log or from DB directly please contact @jakubkrafka to agree on a technical solution
`select * from collection_note where collection_id = 70;`

**Comment by t-mrazek** [comment]
collection.last_update is a date of the running of the scrape-task (consulted with @jakubkrafka).
