### ISSUE TITLE
Data details page is missing a H1 heading

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#80]
The title of the dataset should be a H1 on these pages. Currently it is a H2

<img width="250" alt="Screenshot 2021-06-22 103235" src="https://user-images.githubusercontent.com/11212467/122901265-4ba15300-d345-11eb-9110-11cdbd7255a2.png">

**Comment by t-mrazek** [comment]
h2 changed to h1

**Comment by sabahfromlondon** [comment]
Checked and can see it's now H1, thanks

**Comment by jpmckinney** [comment]
Closing as Deployed.
