### ISSUE TITLE
Update to text for Access Data

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#81]
### Access Data

The OCDS dataset is available to download as a JSON or Excel file.

**JSON Data**

Easily access dumps of data from the Open Contracting Partnership's Kingfisher database. 

**Excel Data**

Easily access data in Excel using the Open Contracting Partnership's Flatten Tool. This tool is designed to help users that prefer data in spreadsheets to either select a small subset of fields / column headings or to customise their spreadsheet output.

<img width="674" alt="Screenshot 2021-06-22 103505" src="https://user-images.githubusercontent.com/11212467/122901559-8e632b00-d345-11eb-987d-d599b158cdd6.png">

**Comment by t-mrazek** [comment]
texts updated

**Comment by sabahfromlondon** [comment]
Perfect, thank you

**Comment by jpmckinney** [comment]
Closing as Deployed.
