### ISSUE TITLE
All feedback pop-ups refer to "UK Contracts Finder"

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#82]
I've checked multiple sources and each time I select the "Contact OCP helpdesk" button on the bottom right, the pop-up message always refers to the dataset as "UK Contracts Finder". 

The heading should refer to the dataset title the user is on when they click the "Contact OCP helpdesk" button

<img width="600" alt="Screenshot 2021-06-22 114746" src="https://user-images.githubusercontent.com/11212467/122912081-ddae5900-d34f-11eb-9d9b-eb8ddad889a9.png">

**Comment by t-mrazek** [comment]
fixed

**Comment by sabahfromlondon** [comment]
This is now missing the country e.g. for 

"Australia Department of finance" only "Department of finance" is coming up. 
"Afghanistan Records" only "Records" is coming up

I think we need to include the name of the country

**Comment by jakubkrafka** [comment]
Done and deployed.

**Comment by sabahfromlondon** [comment]
I've carried out spot checks. Looks good :)
