### ISSUE TITLE
Long and narrow text on data details page

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#83]
Can we move the the paragraphs of text down a bit and have it go across the page a bit more, say up to where I've drawn the red vertical line?

This particular dropdown looks too narrow and too tall.

<img width="552" alt="Screenshot 2021-06-22 115220" src="https://user-images.githubusercontent.com/11212467/122912731-8fe62080-d350-11eb-81d7-a71f46e4fc28.png">

**Comment by hrubyjan** [comment]
Move Available format section to the right (to the Access button). 
Experiment a bit with the design. Keep the same logic as it's now when you have a big window but spread it bellow Available formats and Access button when the window becomes too narrow

**Comment by t-mrazek** [comment]
formats moved, long description refactored.

**Comment by sabahfromlondon** [comment]
I've viewed the following examples and these look much better. Thank you :)

https://data-registry.datlab.eu/en/collection/2
https://data-registry.datlab.eu/en/collection/19

**Comment by jpmckinney** [comment]
Closing as Deployed.
