### ISSUE TITLE
Top header on data details page is not white

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#84]
Just asking because of consistency. Is there any reason why this heading is brown and the others are white?

<img width="875" alt="Screenshot 2021-06-22 115617" src="https://user-images.githubusercontent.com/11212467/122913150-02ef9700-d351-11eb-854e-a6a5a923b2b7.png">

**Comment by hrubyjan** [comment]
no special reason. I guess there were several designs at the beginning with different headers and when we decided we'll use the white one we didn't change it for all other designs and that's how it happened :). We'll change it.

**Comment by t-mrazek** [comment]
white background set

**Comment by sabahfromlondon** [comment]
Perfect, thank you :)

**Comment by jpmckinney** [comment]
Closing as Deployed.
