### ISSUE TITLE
Yellow / white contrast errors

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#86]
Contrast error on both dropdowns on the datasets by country page and on the feedback form.

<img width="181" alt="Screenshot 2021-06-22 120132" src="https://user-images.githubusercontent.com/11212467/122919210-e2770b00-d357-11eb-9910-d00d5bdda48e.png">

Also the option "Last year" below should actually be "Past year"

<img width="140" alt="Screenshot 2021-06-22 120112" src="https://user-images.githubusercontent.com/11212467/122919201-e014b100-d357-11eb-8d43-268fae014fe9.png">

**Comment by hrubyjan** [comment]
Black text and make the field narrower so that it's not far from the dropdown arrow to value selection

**Comment by t-mrazek** [comment]
Black text was set, dropdown width is estimated on the base of the longest option.

**Comment by sabahfromlondon** [comment]
This is much better, thanks

**Comment by jpmckinney** [comment]
Closing as Deployed.
