### ISSUE TITLE
Too much summary text in dataset box

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#87]
I would like to limit the amount of text in the box. In the Canada Buy and Sell example below I think this is too much. 

First preference: Put a word limit in the admin (max 350 characters)
Second preference: Limit text in the box to three lines and add a "... " at the end

<img width="474" alt="Screenshot 2021-07-06 145209" src="https://user-images.githubusercontent.com/11212467/124612082-f21f4500-de69-11eb-96d2-ec086bbd8f33.png">

**Comment by jpmckinney** [comment]
Of those currently in the registry, I ran:

```sql
SELECT id, description_en, LENGTH(description_en) len
FROM data_registry_collection
WHERE description_en IS NOT NULL
ORDER BY len DESC;
```

Canada and Zambia are test data. The next longest is Australia with 255 chars: https://data-registry.datlab.eu/en/collection/19

Australia looks like. We can see how 442 characters look once added.

**Comment by yolile** [comment]
> Australia looks fine. We can see how 442 characters look once added.

https://data-registry.datlab.eu/en/collection/77.  I think it looks fine as well.

**Comment by jpmckinney** [comment]
Yes, 4 lines of text seems fine (half the length of Canada in the issue description).
