### ISSUE TITLE
Dataset detail

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#9]
Detail of the dataset in the Data registry

- there is an old version of ticks. which we will change so that it's in harmony with the selected version of search result item (see #8) 
- Switch for Excel/JSON information in `Available information` section
- updated `Available information` section which now contains more data based on the list provided in #2 
- one section for `Data quality` and `Issues found`
- `ACCESS` button on the top should scroll down to the `Access data` section as user goes here to download the data, therefore, this should be quickly accessible for the user and the page can be long and the `Access data` can be hidden for many users

What's your opinion on this?

![image](https://user-images.githubusercontent.com/17906453/108854847-9bb31780-75e8-11eb-93dc-df9709542ec3.png)

**Comment by sabahfromlondon** [comment]
@hrubyjan 

- Ok so you mean the tick boxes here will change to the Green tick or the grey cross icon - fine
- The toggle switch looks good. maybe try changing the colour so it is more visible? There is a lot of grey on the page
- I think I used "Data quality summary" next to the text box and and "Data quality issues" for the bullet points. Can we have this as a headers? I think these need to be a heading level below what you have used for "Data Quality". Do you see what I mean?
- I like the access button. Now I know it scroll down the page, I think this is fine.

Given the comment from @jpmckinney on #8  I think we can also remove the "Access from OCDS Kingfisher Collect" just below the "Access Data" heading. The sentence can just read "Access data for the date range [date range option]."

Lastly I just noticed the download logo in the top right of the Access data section. I think it looks odd and looks like it is a clickable feature. I suggest we remove this. I'm open you the UI designer trying something different.

**Comment by hrubyjan** [comment]
@sabahfromlondon dateset detail updated


![image](https://user-images.githubusercontent.com/17906453/109950148-7f943200-7cdc-11eb-8ca6-9ece5760ac14.png)

**Comment by jpmckinney** [comment]
@sabahfromlondon Some publishers have custom (e.g. non-Creative Commons) licenses, for which it's hard to determine the reuse terms (especially if written in a different language than the user's language). Even for our own use of their data, we will need to consult lawyers to advice on whether to include them in the registry. As part of that work, we can ask for a brief summary of what is required/allowed/disallowed by the license, and include it on the page. What do you think?

**Comment by sabahfromlondon** [comment]
@jpmckinney yes we had better do this. If what is allowed by the licence is unknown, then it will **not** be good enough to just say so. A brief summary as you described makes sense.

**Comment by jpmckinney** [comment]
I forget what we decided if the dataset had stopped publishing. Do we remove it from the registry? If not, should there be some more prominent indication of the date range covered? It should be clear to the user if the data is not up-to-date.

**Comment by hrubyjan** [comment]
For me it makes sense to keep the dataset present in the data registry even if it stopped publishing. From my experience I can say that for example in Bulgaria one source worked until end of 2019 and they started new source which only contains 2020 and 2021 data. And I have more examples e.g in Estonia two data sources partially overlap but there are data you can't find on the new source. And last but not least is TED :).

The designed processes work with this idea and you are right that there is no such information for the user that the source is no more being updated

**Comment by sabahfromlondon** [comment]
@jpmckinney I agree with @hrubyjan that we should keep the dataset in the registry even if it stopped publishing. It's why I added the 'Last updated' field in the wireframes.

**Comment by jpmckinney** [comment]
Great. I'm currently going through which sources to include in the registry, and there are about 10 for which we can collect data but who have stopped publishing, and then about 70 (about 30 of which are Digiwhist) that are actively publishing.

We can leave the page as-is for now. It just got me thinking that if the number of stopped/paused publishers grows, we should be clearer to the user that this is a concern (unless they're heavily using the date filter, in which case it's no problem).

**Comment by hrubyjan** [comment]
I started new issue #21 to record the last comment but otherwise the general concept of collection detail is ready so I'm closing this issue
