### ISSUE TITLE
Add recent publications

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#92]
Going forward, this issue will not be necessary, as we will add publications as they become available.

* [x] Check all publishers from the March Rapid Reflection are already added
* [x] Collect the publishers from the [June Rapid Reflection](https://docs.google.com/spreadsheets/d/1XHAWQo5w9RVcJJ0-1btQze3CS97Z2RZPdh6rrk8YvU8/edit#gid=456368253), and any new publishers since then

New publications with missing descriptions:

* [x] Instituto Estatal de Transparencia, Acceso a la Información Pública y Protección de Datos Personales de Yucatán (INAIP) (Mexico) [March]
* [x] Instituto de Acceso a la Información Pública (IAIP) (Honduras) [June]
* [x] Instituto Duranguense de Acceso a la Información Pública y de Protección de Datos Personales (IDAIP) (Mexico) [June]
* [x] Instituto Zacatecano de Transparencia, Acceso a la Información y Protección de Datos Personales (IZAI) (Mexico) [June] [DOWN]
* [x] Ebonyi State (Nigeria) [June]
* [x] Slovenia: Ministry of Public Administration [June]
* [x] Indonesia Corruption Watch (ICW) [March]

Publications with descriptions that needs to be added to the data registry:

* [x] Moldova 
* [x] Perú
* [x] Ghana Public Procurement Authority (PPA) (Ghana) [new]
* [x] Québec: Secrétariat du Conseil du trésor (Canada) [June]
* [x] Narodne Navine d.d. (Croatia) [June]

I've created an [issue template](https://github.com/open-contracting/data-registry/blob/main/.github/ISSUE_TEMPLATE/new-publication.md) with all the steps to add a new publication.

Am I missing any steps, @hrubyjan ?

We can document some of the process in an administrator's manual if the issue template is not sufficient.

**Comment by jpmckinney** [comment]
@yolile When preparing that list of 9 publications, did you compare against the Google Doc or against the admin panel? If any others are missing from the admin panel, please ask Jan to start their processing.

**Comment by yolile** [comment]
> If any others are missing from the admin panel

I would love to get into the admin panel, but even after several attempts the login is still not working for me :(

**Comment by jpmckinney** [comment]
@yolile I've copy-pasted the list here: https://docs.google.com/spreadsheets/d/1OmL53-_PLPgJZFqxx0iwHRbRvB597bKPo5Kl6vuA_7U/edit#gid=1714812423 If any are ambiguous, just ask @hrubyjan.

**Comment by yolile** [comment]
> If any others are missing from the admin panel, please ask Jan to start their processing.

I've checked it and updated the issue description now. @hrubyjan could you start the process for `peru_compras` and I'm not sure we were using `moldova` or `moldova_old` for Moldova, so if it was `moldova_old`, please use `moldova` instead

**Comment by yolile** [comment]
We need to re-deploy kingfisher-collect in order to have the spiders for the remaining publishers.

**Comment by hrubyjan** [comment]
@yolile we are redeploying all components quite often so it's probably been redeployed. Unfortunately Jakub is out of office now so I cannot confirm with him but you can try. I'll confirm with him once he's back.

**Comment by yolile** [comment]
@hrubyjan nop, I don't see the new ones yet

**Comment by yolile** [comment]
> Going forward, this issue will not be necessary, as we will add publications as they become available.

@jpmckinney  As we have a process for adding new publications in the CRM and also tracking their inclusion to the registry in the MEL 1 sheet, I think we can close this issue now (and we already added all the publications listed in this issue)
