### ISSUE TITLE
Order disk drives

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#94]
@hrubyjan What is @jakubkrafka's opinion? If none, I'll just order two 16TB HDDs (rotational).

**Comment by hrubyjan** [comment]
I was waiting to see how big will be the exported dumps. 
- Currently for example Digiwhist Germany (which has roughly 500k compiled releases) takes 765MB. 
- 30 data sources all together takes 15GB. 
- The biggest sources are in progress (France 3 million compiled releases, Polans 3 Million, Romania 20 Million). 
- Simple calculation says that 30M compiled release remains. 
- That is 60 * 765MB = 50GB. Two versions of data together less then 200GB

So this seems to be to no game changer between 8TB a 16TB disk.
The postgres itself takes currently 500GB but the largest Digiwhist datasets are nor processed yet so it can grow up to 1TB and it's just one version

My quick calculations says we should be safe with 8TB disk. But I don't now what are requirements for spoonbill and I maybe also forgot some important fact so I rather let @jakubkrafka react too :)

**Comment by jpmckinney** [comment]
It looks like 8TB is not an option (6, 12 or 16): https://www.hetzner.com/additional-hardware/

I am fine with any size, and I don't mind following generous estimates. Making a change later will be more expensive.

**Comment by jpmckinney** [comment]
For Spoonbill, the greatest demand for disk space will be from the registry's datasets, since users are not expected to upload files of that magnitude.

If, at a later date, we decide to pre-calculate the "OCDS Lite" versions of datasets, then this would require a multiple of the input JSON. @sorenabell can share any other information.

But, in general, if we're already at 8TB to be safe for the registry, and the choice becomes between 12TB and 16TB (since Hetzner doesn't offer 8), then we can just do 16TB.

**Comment by hrubyjan** [comment]
Ordered, mounted. We are moving the data to right now
