### ISSUE TITLE
Full-name country filter (was: Landing pages per country)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#96]
During a demo to the OCP team, they asked whether it was possible to list all publications for a specific country.

I suppose we have a few options:

* Have landing pages per country, e.g. `/country/mx`, and otherwise use a similar layout to the search page.
* Change the letter filter to a country filter.
  * The filter should be reflected in the URL (query string or fragment), so that we can share links.
* Do nothing. Users can select the starting letter.

cc @sabahfromlondon

**Comment by sabahfromlondon** [comment]
I looked into country pages and publisher pages during the user research. 

That high level view of publications in a country doesn't really add value to the end user, especially as it's addressed by clicking the starting letter.

What is more useful to users is getting a detailed picture of what is in the dataset e.g. in the UK Crown Commercial Service dataset, they want to know if there is data for Birmingham City Council. Challenging I know, but that's what's valuable.

Please can we go with the do nothing option?

**Comment by jpmckinney** [comment]
I'm fine with do nothing! I don't think it's a special burden for users to click one filter and scroll a bit.

**Comment by yolile** [comment]
Note that we don't need country pages, just a filter by country (e.g no extra descriptions or landing pages), basically, option 2

> Change the letter filter to a country filter.
> The filter should be reflected in the URL (query string or fragment), so that we can share links.

**Comment by jpmckinney** [comment]
From Slack:

We can replace the current alphabet country filter with a country dropdown. We can decide whether to have an info icon and tooltip to explain that unlisted countries have no datasets (that is the only reason I can think of for using letters).
