### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#97]
OCP:

* [x] Translate UI to Russian 
* [x] Translate dataset text to Russian

OCP's tasks depend on finalizing the UI text #95.

Datlab:

* [x] Add Russian as language option
* [x] Add option to admin for Russian text

**Comment by yolile** [comment]
All tasks are done now. Note that we only translated Moldova and Kyrgyz into Russian as agreed with the OCP team.
