### ISSUE TITLE
Send feedback email

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#98]
Based on discussion in #64 

James sent SMTP credentials to slack

User can share the feedback by going to dataset detail -> Contact OCP helpdesk -> Submit feedback

**Subject**
You have new feedback on the [dataset country and title] dataset.

**Email body content**
The following feedback was provided for the [dataset country and title] dataset.

Type of feedback: [type of feedback dropdown option selected]
Feedback detail: [content of feedback in text field]

The feedback should be followed up with in the data registry by either fixing the issues e.g. a broken link, or by proving further advice and guidance to users.

**Comment by jakubkrafka** [comment]
Done and deployed. Just a side note - there are multiple email used on the site (see footer for example). Maybe, we should unite them.

**Comment by jpmckinney** [comment]
I tested it. I received an email. 👍

**Comment by jpmckinney** [comment]
I think engage@ in the footer is fine. The email will eventually be directed to the correct person. I don't know if there are even more emails.
