### ISSUE TITLE
Registry admin clarification of fields

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#99]
Feedback from testing with @yolile on this page.:

<img width="643" alt="Screenshot 2021-07-29 142549" src="https://user-images.githubusercontent.com/11212467/127500061-d82b9feb-3c86-4d10-a40b-1573006a0822.png">

I know you're writing a guide for users, so hope this helps. I do think that clearer descriptions of fields should be provided in the interface itself though, rather than in a separate document.

* Free text is odd for these fields: Country, Language - should be selectable i.e. a dropdown like we have for the country flags.
* [x] User needs to have an explanation of what Language field is. How about "The language that the publisher has provided data in"
* [x] What is the different between "Description" and "Description long"? - I assume this is for where the different description lengths go but this should be explained in the UI
* [x] There should be instructions to tell the user that they need to provide content in English for the English tab and in Spanish for the Spanish tab - and they they need to fill out both!
* [x] It was not clear what the difference between "License" and "License custom" is
* [x] Is the "Summary" field for the data quality summary? If so, that is what we should call the field
* [x] Additional data  field - not clear what type of information should be provided here.
* [x] Public / frozen  - this was confusing
* [x] It was not clear why the date fields are manual
* [x] The count fields - not sure what the user needs to do here

**Comment by jpmckinney** [comment]
For Country and Language, we'd need dropdowns for every language (English, Spanish, Russian). I think it is fine to enter these manually. If we typo, we can just edit later.

I'll address all other issues, having now confirmed the semantics with Jan on a call with Yohanna.
